### ISSUE TITLE
ArcGIS Plugin with 3d features excluded breaks graphics layer rendering and drawing tools

### ISSUE THREAD

**Issue by bishrant** [Esri/arcgis-webpack-plugin#102]
While instantiating a new ArcGISPlugin if features has "3d" and if its is set to false (to exclude it), the drawing tools, specifically the SketchViewModel fails along with graphics visualization.

## Description
This configuration for webpack works
```javascript
const ArcGISPlugin = require("@arcgis/webpack-plugin");

module.exports = {
  plugins: [new ArcGISPlugin({
      features: {
        "3d": true
      }
  })],
  node: {
    process: false,
    global: false,
    fs: "empty"
  }
};
```

but this does not

```javascript
const ArcGISPlugin = require("@arcgis/webpack-plugin");

module.exports = {
  plugins: [new ArcGISPlugin({
      features: {
        "3d": false
      }
  })],
  node: {
    process: false,
    global: false,
    fs: "empty"
  }
};
```

It was working until 4.16.

## Expected Behavior
3D modules to be excluded from the build.

## Actual Behavior
Drawing is not visible in the map. Draw seems to draw the features but not visible to human eye.

## Possible Fix
Possibly look into `lib/features.js` towards the line where 3d features are excluded
`return input.includes(x) || (input.includes("arcgis-js-api") && input.includes("3D"));` 
if we omit that `input.includes("3D"` it works

## Steps to Reproduce

1. Start with https://github.com/bishrant/jsapi-resources/tree/master/4.x/webpack/demo
2. Update `index.ts` to add a simple graphic on map load
3. Append this at the end of the file 
``` javascript
import Graphic from 'esri/Graphic';
import SimpleLineSymbol from 'esri/symbols/SimpleLineSymbol';
import Polyline from 'esri/geometry/Polyline';
view.when((f: any) => {
  const polyline: any = new Polyline({
    spatialReference: {wkid: 4326},
      paths: [[
        [-111.30, 52.68],
        [-98, 49.5],
        [-93.94, 29.89]
      ]]
  });
  const polylineSymbol = new SimpleLineSymbol({
    color: [226, 119, 40],
    width: 4
  });

  const polylineGraphic = new Graphic({
    geometry: polyline,
    symbol: polylineSymbol,
  });
  
  view.graphics.add(polylineGraphic);
})
```

4. run `npm start`

## Context
It appeared after 4.17 release. All these things were working in 4.16

## Your Environment

* Version used: 4.17.3
* Browser Name and version: Google Chrome 86.0.4240.111
* Operating System and version (desktop or mobile): Desktop
* Link to your project if available: https://github.com/bishrant/jsapi-resources/tree/master/4.x/webpack/demo/src

**Comment by odoe** [comment]
Don't use this feature for now, there is some cross-dependencies for 2d and 3d graphics at the moment and we can't cleanly exclude 3d features from the build.
