### ISSUE TITLE
Cannot use feature layer with 4.17: Accessor#set Invalid property

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-webpack-plugin#103]
## Description
Since I upgraded my application to 4.17 with arcgis-webpack-plugin, feature layers are no longer displayed and the following error is logged:

```[esri.core.Accessor] Accessor#set Invalid property value, value needs to be one of 'esri.symbols.SimpleFillSymbol', 'esri.symbols.PictureFillSymbol', 'esri.symbols.PictureMarkerSymbol', 'esri.symbols.SimpleLineSymbol', 'esri.symbols.SimpleMarkerSymbol', 'esri.symbols.TextSymbol', 'unknown', 'unknown', 'unknown', 'unknown', 'unknown', 'esri.symbols.CIMSymbol', or a plain object that can autocast (having .type = 'simple-fill', 'picture-fill', 'picture-marker', 'simple-line', 'simple-marker', 'text', 'line-3d', 'mesh-3d', 'point-3d', 'polygon-3d', 'web-style', 'cim')```

## Expected Behavior
Feature layer should be displayed

## Actual Behavior
Feature layer is not displayed

## Steps to Reproduce

To reproduce the issue, I created a simple application using arcgis-cli 4.16 and updated it to 4.17. The feature layer is not displayed and the error is logged.
1. git clone https://github.com/Biboba/arcgis-webpack-feature-layer.git
2. npm run start

Pretty much the same code works using CDN version:
https://codepen.io/dgskhjgrhjgwi/pen/MWebKvG

## Context
I upgraded my application using arcgis-webpack-plugin from 4.16 to 4.17.

## Your Environment

* Version used: 4.17.4
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile):
* Link to your project if available:

Thanks !

**Comment by odoe** [comment]
This should be fixed in `4.17.5`

Note, that if there is still issues, remove the `"3d": false` features option. I had to remove some modules from the exclude list for the 4.17 release.

**Comment by Biboba** [comment]
Thanks, indeed it solved the issue.
Unfortunately, I found a bug with the editor widget in 4.17 (BUG-000134789). Will have to wait for 4.18 !

Thanks for the quick fix anyway !

**Comment by hgonzago** [comment]
@Biboba by chance, do you know if the service you are trying to edit supports pbf format?

**Comment by Biboba** [comment]
@hgonzago no indeed. It does not support pbf format.
When opening the case, I noticed that the issue only occured on standalone feature services and not on hosted feature services. pbf might be the difference !

**Comment by Biboba** [comment]
@hgonzago FYI, I can no longer reproduce the issue using CDN version nor nom arcgis-js-api package.
Did you release a fix ? Thanks

**Comment by hgonzago** [comment]
@Biboba yes, we patched this late last week.
