### ISSUE TITLE
esri_geometry__WEBPACK_IMPORTED_MODULE_3__.projection is undefined

### ISSUE THREAD

**Issue by apaleja** [Esri/arcgis-webpack-plugin#108]
I am trying to use the `esri/geometry/projection` module:
```
import {SpatialReference, projection} from "esri/geometry";


polygon.geometry = projection.project(polygon.geometry, SpatialReference.WGS84);
```

Getting error : `Uncaught TypeError: esri_geometry__WEBPACK_IMPORTED_MODULE_3__.projection is undefined`

# FYI: 
- based on comment on  issue #8 , I have verified my webpack config already have `node globals`:
```
// webpack.config.js
  node: {
    process: false,
    global: false,
    fs: "empty"
  }
```
- I am using Version: 4.17

Any guidance will be helpful.

**Comment by odoe** [comment]
Doesn't look like projection is available from the esri/geometry entry module. You'll need to import it directly.
https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry.html

**Comment by apaleja** [comment]
@odoe Thanks for your reply. What do you mean by import it directly ? from the ESRI's CDN ?

**Comment by dasa** [comment]
Try `import * as projection from "esri/geometry/projection";`

**Comment by apaleja** [comment]
@dasa Thanks for your reply. It surely worked but now I am getting below error:

```
Uncaught TypeError: Cannot read property '_getTransformation' of null
    at f (projection.js:25)
    at s (projection.js:25)
    at Object../node_modules/arcgis-js-api/geometry/projection.js.__webpack_require__.dj.d.n.project (projection.js:25)
```

I am sure syntax is correct. am I missing sometihng here ?
```
import SpatialReference from "esri/geometry/SpatialReference ";
import * as projection from "esri/geometry/projection";


polygon.geometry = projection.project(polygon.geometry, SpatialReference.WGS84);
```

**Comment by dasa** [comment]
Hi, you must wait for it to load first: https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-projection.html#load

**Comment by apaleja** [comment]
@dasa Thanks for pointing me to the right direction it worked for me.
