### ISSUE TITLE
Uncaught ReferenceError: process is not defined from a third party library

### ISSUE THREAD

**Issue by NunuLi** [Esri/arcgis-webpack-plugin#110]
I got into a situation where the process has to be true, otherwise an error "process is undefined" is thrown from other packages. Why we need to set process = false here and how can we solve the conflict?

_Originally posted by @NunuLi in https://github.com/Esri/arcgis-webpack-plugin/issues/41#issuecomment-809852353_

**Comment by andygup** [comment]
Closing issue in preparation for repo archiving.
