### ISSUE TITLE
SSH fetching dojo/utils package in 4.17.5 version

### ISSUE THREAD

**Issue by yevhenii-username** [Esri/arcgis-webpack-plugin#111]
Error while building project with dependency - "@arcgis/webpack-plugin": "4.17.5",

### it's an error from CI
![image](https://user-images.githubusercontent.com/17275749/115400039-7bbb6100-a1f1-11eb-831a-4b27cbeb04ee.png)

### its node modules from @arcgis/webpack-plugin package. 
![image](https://user-images.githubusercontent.com/17275749/115400095-8bd34080-a1f1-11eb-815e-1dc94c99ea7b.png)

## Expected Behavior

Build without trying to fetch dojo/utils through ssh

## Actual Behavior

Try to get through ssh

## Possible Fix

change ssh to https fetchig

## Steps to Reproduce

1. Install @arcgis/webpack-plugin": "4.17.5

## Your Environment

* Version used: 4.17.5
* Node 16.14.1
* Browser Name and version: -
* Operating System and version (desktop or mobile): Ubuntu 20.04.2 LTS
* Link to your project if available: -

**Comment by odoe** [comment]
You can configure git alias.
`git config --global url."https://".insteadOf git://`

This is first time issue has come up, so I would rather not change it. We are not updating older versions unless absolutely needed at this point.

**Comment by andygup** [comment]
Closing issue in preparation for repo archiving.
