### ISSUE TITLE
Regression for assetsDir option

### ISSUE THREAD

**Issue by Zhumos** [Esri/arcgis-webpack-plugin#114]
## Description

Commit https://github.com/Esri/arcgis-webpack-plugin/commit/7aadbb185b1611ee20574002c5ae2dd8e7a5e444 regressed from using the value of the assetsDir option as the target copy path to instead use "assets"

## Expected Behavior

Assets should be copied to path specified by assetsDir

## Actual Behavior

Assets are always copied to the path "assets" regardless of the value of assetsDir

**Comment by Biboba** [comment]
@odoe, could we have a release for that bug ?

**Comment by odoe** [comment]
There will be an update on this coming Friday or Monday

**Comment by andygup** [comment]
Closing issue in preparation for repo archiving.
