### ISSUE TITLE
Enhancement: version static assets by default

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-webpack-plugin#116]
Following an issue while upgrading my application, I wonder if static files should not be versionned by default by the 'arcgis-webpack-plugin'.

## Description

When deploying an application upgraded from ESRI JS API 4.19 to 4.21 on a webserver, I had a bunch of error like the following:
![static_error](https://user-images.githubusercontent.com/11556423/145246334-d8aa4739-cb16-4c37-b9ef-9639ad5b873c.JPG)

I also had a warning message saying that static files version is different (4.19) from js api version (4.21). So to avoid that I tried to version the static files and it worked no issue .  Just like on the CDN, which are available at:
https://js.arcgis.com/[4.x]/@arcgis/core/assets

My application is displaying vectorTiles in regional WKID as default basemap. Could it be related for example to the coordinates conversations that I believe the .wasm file may be doing ? Just trying to guess !

Don't you think it's not safer to do so the same ? And rather than `assets`, assetsDir variable could default to `/assets/[4.x]/` ?

Thanks for listening !

**Comment by andygup** [comment]
Closing issue in preparation for repo archiving.
