### ISSUE TITLE
4.17.6 broken: Error: Dojo loader version does not match the version of Dojo.

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-webpack-plugin#117]
My application built with @arcgis/webpack-plugin 4.17.5 can no longer be built.

## Description

Running webpack:

```
Error: Dojo loader version does not match the version of Dojo.
Loader version = 1.16.4.
Dojo version = 1.17.3.
You may need to rebuild the Dojo loader.
Refer to https://github.com/OpenNTF/dojo-webpack-plugin/blob/master/README.md#building-the-dojo-loader
```

## Expected Behavior
Application built successfully.

## Actual Behavior
Build fails

## Possible Fix
#100, #112

Thanks !

## Your Environment

* Version used: 4.17.6
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by odoe** [comment]
I'm assuming you are also using `arcgis-js-api@4.17`? At version 4.18, the dojo-webpack-plugin dependency was removed.

But if you need this for 4.17, you will need to create your own dojo loader as described here
https://github.com/OpenNTF/dojo-webpack-plugin/blob/master/README.md#building-the-dojo-loader

And you can add it to the `@arcgis/webpack-plugin` via the `options` param to add your own loaderConfig
https://github.com/Esri/arcgis-webpack-plugin/blob/96c60c8d469e4976d1b62ec30b4c9838e4d74480/README.md#options

**Comment by Biboba** [comment]
I added my own dojo loader via the options and it now works.
Thanks @odoe for your quick reply and suggestion. Much appreciated !
