### ISSUE TITLE
Support create-react-app React apps

### ISSUE THREAD

**Issue by ssylvia** [Esri/arcgis-webpack-plugin#12]
## Description

The current version of the plugin is incompatible with react apps created with the create-react-app (CRA) CLI. This includes creating a custom fork of CRA to add the arcgis webpack plugin

A couple issues I encountered:
- The CRA ModuleScope plugin fails because the dojo modules don't have a context object applied to them: https://github.com/facebook/create-react-app/blob/next/packages/react-dev-utils/ModuleScopePlugin.js#L25.
- Also, it looks like the node-global (https://webpack.js.org/configuration/node/#node-global) configuration needs to be `true` for other plugins that CRA uses.

## Steps to Reproduce

1. Create fork of Create React App
2. Modify fork `react-scripts` package to add the basic `@arcgis/webpack-plugin` configuration
3. Create a new react app with the `react-scripts` package set to this custom fork
4. Load a webmap

**Comment by g3r4n** [comment]
Hi @ssylvia, I've faced the same issue and create [arcgispack](https://github.com/g3r4n/arcgispack) and [arcgis-wrapper](https://www.npmjs.com/package/arcgis-wrapper) to fix this issue. 
Arcgispack let you create a bundle of the ArcGIS JS API with Webpack (without any configuration change of your current workflow) and arcgis-wrapper let you require module of the custom ArcGIS JS API bundle.
There is a full version of the API stored into one bundle : https://cdn.jsdelivr.net/gh/g3r4n/arcgispack@0.0.24/esri-bundle/bundle.js

Here is an example for your case: 
https://github.com/g3r4n/arcgispack-cra-example

Here is the same example in codesandbox:
https://codesandbox.io/s/k30nlqkr37?module=%2Fsrc%2FReactSceneView.js

let me know what you think about it.

**Comment by steveoh** [comment]
I would like to see this plugin an the arcgis pack/wrapper that @g3r4n created merge. I'll help in any way I can. Figure it out!

**Comment by tomwayson** [comment]
I don't fully understand how arcgispack / arcgis-wrapper work, but this scares me:

> There is a full version of the API stored into one bundle

@g3r4n 

Does that bundle have _all_ the JSAPI modules, regardless of whether or not you are going to use them in your app?

Looking at the network traffic in the codesandbox example above, that bundle seems to be 6.53MB.

Does that^^^ need to load before the rest of the app? Can it be lazy loaded only when the map is needed (i.e. can we use code splitting, ideally dynamic `import()` with that?

**Comment by tomwayson** [comment]
OK, it looks like you can configure arcgispack to only include the modules you need:

https://github.com/g3r4n/arcgispack-cra-example/blob/master/arcgis.config.js#L5

**Comment by nightsu** [comment]
@ssylvia  Hi, have you resolved the problem?

**Comment by tomwayson** [comment]
@nightsu I don't believe that anyone is actively working on this issue, but you can always use [esri-loader](https://github.com/Esri/esri-loader) with create-react-app. Here's an example application: [create-arcgis-app](https://github.com/tomwayson/create-arcgis-app/) .

You can also read more about when to use this [webpack plugin vs esri-loader](https://developers.arcgis.com/javascript/latest/guide/using-frameworks/#when-to-use-the-webpack-plugin-vs-esri-loader).

**Comment by boualikamel** [comment]
check this, it can help !

https://github.com/Esri/arcgis-webpack-plugin/issues/76#issuecomment-575931414
