### ISSUE TITLE
ArcGIS font's fail to load

### ISSUE THREAD

**Issue by roemhildtg** [Esri/arcgis-webpack-plugin#15]
I've configured my arcgis app to not use the default loaders. 

```javascript
        new ArcGISPlugin({
             useDefaultAssetLoaders: false,
        }),
```
This is because I'm including some additional libraries like font awesome. 

In summary, I'm running into issue with fonts:

Failed to decode downloaded font: <URL>
OTS parsing error: invalid version tag 

This occurs in production and in webpack-dev server builds.

Same error as mentioned, hopefully we can trouble shoot this here a bit and figure out what the issue is so folks won't run into this in the future.

The network log shows these fonts being loaded twice, which I find odd:

![image](https://user-images.githubusercontent.com/5471079/40429276-eb2ac7c2-5e67-11e8-8343-ff248824351f.png)

This issue is discussed here...it mentions a potential cause of using multiple loaders for the same file, which might be the cause here since arcgis plugin is using its own loaders under the hood. Not sure though. 

https://github.com/webpack-contrib/file-loader/issues/84#issuecomment-240958596

## Steps to Reproduce
1. Download https://github.com/roemhildtg/arcgis-webpack-font-issue
2. `npm install && npm start`
3. Browse to [http://localhost:9000](http://localhost:9000)
4. Observe font issues

## Context
I was trying to create a webpack app from scratch. The reason being there's tons of guides out on the web and you really don't know the best way to do so without doing it by hand once. The esri starter template is nice and is probably packed with tons of features that I don't even know I need yet, but I can't understand how to fix issues I encounter without building up an environment from scratch. 

## Your Environment
* Version used: Latest on github (4.7.10)
* Browser Name and version: Chrome 66
* Operating System and version (desktop or mobile): Windows 7
* Link to your project if available: https://github.com/roemhildtg/arcgis-webpack-font-issue

**Comment by odoe** [comment]
Found this issue and I think I have a fix,

The options aren't copied to the plugin correctly.

```js
this.options = { ...this.options, ...options.options };
```

should be

```js
this.options = { ...this.options, ...options, ...options.options };
```

I wrote some unit tests to help cover this, but having an issue trying to create more than a single webpack instance to test multiple configurations. I'll push an update soon in `4.7.11`

**Comment by odoe** [comment]
Even that might need to be cleaned up. Maybe I'll just say that you can override any of the [dojo-webpack-plugin options](https://github.com/OpenNTF/dojo-webpack-plugin#options) directly. I just don't want to expose them to the user.

**Comment by roemhildtg** [comment]
What about `Object.assign({}, this.options, options, options.options)`? Not that it fixes this font issue though...I just did a quick test to see and same result so far...

**Comment by odoe** [comment]
This should be fixed in [`4.7.11`](https://github.com/Esri/arcgis-webpack-plugin/releases/tag/4.7.11)

Could you try that out @roemhildtg?

**Comment by roemhildtg** [comment]
Woo! It works! Beautiful :+1: 

I'll keep that tip in mind. My actual app is a bit more complex, and so far I think I'm good by just importing the sass like this:

import 'arcgis-js-api/themes/light/main.scss';
import 'arcgis-js-api/themes/light/view.scss';

**Comment by odoe** [comment]
Awesome, thanks!

**Comment by roemhildtg** [comment]
So now I'm getting fancy. I'm loading the scss from my `main.scss` file using 
```
@import '~esri/themes/light/main.scss';
@import '~esri/themes/light/view.scss';
```

So that I can override some of the variables (ie color). Now its having an issue finding the relative path to dgrid. Any suggestions for fixing this error message?
```
ERROR in ./src/styles/main.scss (./node_modules/css-loader!./node_modules/resolve-url-loader??ref--8-2!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles/main.scss)
    Module not found: Error: Can't resolve '../../../dgrid/css/dgrid.css' in 'c:\Users\web\datalink\src\styles'
     @ ./node_modules/css-loader!./node_modules/resolve-url-loader??ref--8-2!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles/main.scss 6:10-90
```

**Comment by roemhildtg** [comment]
Relevent webpack:
```javascript

        }, {
            test: /\.css$/,
            use: [
                MiniCssExtractPlugin.loader,
                {loader: 'css-loader', sourceMap: true}, {
                    loader: 'resolve-url-loader',
                    options: {includeRoot: true},
                },
            ],
        }, {
            test: /\.less$/,
            use: [
                MiniCssExtractPlugin.loader,
                'css-loader',
                'less-loader',
            ],
        }, {
            test: /\.scss$/,
            use: [
                MiniCssExtractPlugin.loader,
                {loader: 'css-loader', sourceMap: true}, {
                    loader: 'resolve-url-loader',
                    options: {includeRoot: true},
                }, {
                    loader: 'sass-loader',
                    options: {
                        sourceMap: true,
                    },
                },
            ],
        }, {
```

**Comment by odoe** [comment]
You need this sass variable if using the JSAPI sass

`$include_RasterSymbologyEditor: false !default;`

It's pulling in the dgrid css and I don't know why the `resolve-url-loader` can't pick it up.
