### ISSUE TITLE
Slow build

### ISSUE THREAD

**Issue by tgeorges** [Esri/arcgis-webpack-plugin#16]
Hi all,

## Description
We have integrated your plugin in 2 projects and we experience slow build process in both of them. We understand that it is caused by the sub process of building avery time all AGS API dependencies (like dojo, etc). 

## Expected Behavior

Is there a way to limit this in a layer (like in dojo builds) which will not be refreshed every time a file change on the filesystem with your webpack plugin ?

## Actual Behavior

Whole apis rebuild

## Steps to Reproduce

1. clone https://github.com/odoe/jsapi-webpack
2. add a component
3. modify it
4. check build time

## Your Environment

* Version used: 4.7.11
* Browser Name and version: chrome last
* Operating System and version (desktop or mobile): OSX HS
* Link to your project if available:

**Comment by roemhildtg** [comment]
Can confirm, the webpack dev server takes a long time to build the first time, but after updating/auto-reloading the builds are really quick.

**Comment by tgeorges** [comment]
Hi,

Thanks for your feedback. @odoe, I try your update on the sample ES6 project this morning.
I see that you add support for the scss assets in webpack, good thing for your sample ;-)

Let you know quickly what happens on my side

**Comment by tgeorges** [comment]
On my side, I experienced 10->12 seconds build time on dev server. The first time take about 100 seconds.
I will check your progression on DllPlugin, It sounds to be a good idea.

Thanks for your time & help

(you can close this issue)
