### ISSUE TITLE
can't load json file when add this plugin at webpack

### ISSUE THREAD

**Issue by vanmap** [Esri/arcgis-webpack-plugin#23]
## Description

without new ArcGISPlugin(), then I can load json file as 
import setting from './setting.json';
However, if add new ArcGISPlugin(), then compile failed with message:
ERROR in ./src/setting.json (./node_modules/ts-loader??ref--4!./src/setting.json)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by roemhildtg** [comment]
I've been able to load json files without issue. Are you sure your json is valid?

**Comment by odoe** [comment]
To add to that, how is your json loader in webpack config set up?

Here is what I've used in the past.

```
{
    type: 'javascript/auto',
    test: /\.json$/,
    use: [
        {
          loader: 'file-loader'
        }
    ]
}
```

**Comment by vanmap** [comment]
according document: https://webpack.js.org/loaders/json-loader/, I didn't set rules for json loader. 

I use the example from https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo
the webpack.config.js as:

const ArcGISPlugin = require("@arcgis/webpack-plugin");
const CleanWebpackPlugin = require("clean-webpack-plugin");
const HtmlWebPackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");

const path = require("path");

module.exports = {
  entry: {
    //index: ["./src/css/main.scss", "./src/index.ts"]
    index: ["./src/index.ts"]
  },
  output: {
    filename: "[name].[chunkhash].js",
    publicPath: ""
  },
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        cache: true,
        parallel: true,
        sourceMap: true
      })
    ]
  },
  module: {

    rules: [
      {
        test: /\.tsx?$/,
        loader: "ts-loader",
        options: {
          transpileOnly: true
        }
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader",
            options: { minimize: false }
          }
        ],
        exclude: /node_modules/
      },
      {
        test: /\.scss$/,
        use: [
          MiniCssExtractPlugin.loader,
          "css-loader",
          {
            loader: "resolve-url-loader",
            options: { includeRoot: true }
          },
          "sass-loader?sourceMap"
        ]
      }
      
    ]
  },
  plugins: [
    new CleanWebpackPlugin(["dist"]),

    new ArcGISPlugin(),

    new HtmlWebPackPlugin({
      title: "ArcGIS Template Application",
      template: "./src/index.html",
      filename: "./index.html",
      favicon: "./src/assets/favicon.ico",
      chunksSortMode: "none",
      inlineSource: ".(css)$"
    }),

    new MiniCssExtractPlugin({
      filename: "[name].[chunkhash].css",
      chunkFilename: "[id].css"
    })
  ],
  resolve: {
    modules: [
      path.resolve(__dirname, "/src"),
      path.resolve(__dirname, "node_modules/")
    ],
    extensions: [".ts", ".tsx", ".js", ".scss", ".css"]
  },
  node: {
    process: false,
    global: false,
    fs: "empty"
  }
};


and index.ts:
import setting from './setting.json';
//var setting = require('json-loader!./setting.json');

console.log(setting.test);

I get error message:
ERROR in ./src/setting.json (./node_modules/ts-loader??ref--4!./src/setting.json)
Module parse failed: Unexpected token d in JSON at position 0 while parsing near 'define(["require", "...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token d in JSON at position 0 while parsing near 'define(["require", "...'

and the setting.js file : {"test":"app test"}

**Comment by roemhildtg** [comment]
Is your file called `setting.js` or `setting.json`? Try renaming it to .json if its not.

**Comment by vanmap** [comment]
it is called setting.json

**Comment by roemhildtg** [comment]
Typescript is weird with the import syntax. Try using this:

const settings = require('./settings.json');

**Comment by vanmap** [comment]
it can build but get run-time error:
index.8033d5b4348c48502264.js:165 Uncaught Error: Module not found: src/setting.json
    at findModule (index.8033d5b4348c48502264.js:165)
    at contextRequire (index.8033d5b4348c48502264.js:186)
    at result (index.8033d5b4348c48502264.js:108)
    at eval (index.ts:3)
    at eval (index.ts:5)
    at Object../src/index.ts (index.8033d5b4348c48502264.js:572)
    at __webpack_require__ (index.8033d5b4348c48502264.js:20)
    at eval (webpack:///multi_(:8080/webpack)-dev-server/client?:2:1)
    at Object.0 (index.8033d5b4348c48502264.js:583)
    at __webpack_require__ (index.8033d5b4348c48502264.js:20)

from broswer debug, i can see index.ts with code:
var setting = require('./setting.json');

if i commented out new ArcGISPlugin() from plugins of webpack.config.json, The  it works.
I can see from browser debug, it is:
   var setting = __webpack_require__(/*! ./setting.json */ "./src/setting.json");

it changes from require to __webpack_require.

**Comment by odoe** [comment]
I think I found the issue, but it I need to bubble it up to the dojo-webpack-plugin repo. I'll need to prepare a simple test case first and make an issue to see if it's fixable.

Thanks!

**Comment by odoe** [comment]
This should work as expected with no extra work using babel and in TS you can add `"resolveJsonModule": true` to your `tsconfig.json`.
