### ISSUE TITLE
3.26 support

### ISSUE THREAD

**Issue by tgeorges** [Esri/arcgis-webpack-plugin#25]
Hi Webpack Team !

## Description
We have some project that we support and they are using 3.26 API. As bower is not a good option for future release, we are asking if we can use this plugin with 3.x or an adapted version.
Did you have any feedback using it ?

## Expected Behavior
Build 3.26 project with web pack

## Actual Behavior
Build with classic dojo build

## Context
it is not a bug, it is a feature request

**Comment by tomwayson** [comment]
@odoe can correct me if I'm wrong, but AFAIK there is no plan for a webpack plugin to support building 3.x.

There's always [esri-loader](https://github.com/Esri/esri-loader).

**Comment by tgeorges** [comment]
Yes, actually its an alternative for using npm. But its not a good option for us to migrate from a dojo build to a webpack + CDN for Esri library.

**Comment by tomwayson** [comment]
FYI - esri-loader can [also point to a local build of the JSAPI](https://github.com/Esri/esri-loader/issues/130#issuecomment-420712705) instead of the CDN. I mean you would either download the SDK or do a local dojo build of the JSAPI, and then use webpack to bundle you app w/ esri-loader, which points to the locally hosted API.

**Comment by tgeorges** [comment]
Yes it can be an option. The problem is that I will probably have to determine the dependencies to the api manually instead of what is done by the dojo loader actually, and its not very productive and potentially error source. But ok, I keep it in mind. 
Anyway, @odoe can you please tell us if you have a plan or a sample for 3.x that can help us ?
Thanks !

**Comment by odoe** [comment]
This is still something being tested with a bower install of 3x, as 3x cannot be installed via npm. It will probably be a while though, as I have commitments up to the middle of November.

**Comment by tgeorges** [comment]
Thanks @odoe for your feedback. Its not urgent for us. If you have some ideas when you'll have more time it can help us.
Good luck for all of your commitments
