### ISSUE TITLE
Install of arcgis-webpack-plugin 4.9.0 fails

### ISSUE THREAD

**Issue by atdiff** [Esri/arcgis-webpack-plugin#27]
## Description

When running an npm install or yarn install with a package.json containing arcgis-webpack-plugin, it fails with error:
> Couldn't find package "@dojo/framework@^3.0.1" required by "arcgis-js-api@~4.9.0" on the "npm" registry.

## Expected Behavior

npm/yarn install should work successfully and arcgis-js-api should be installed in the node_modules folder

## Actual Behavior

Install fails with error:
> Couldn't find package "@dojo/framework@^3.0.1" required by "arcgis-js-api@~4.9.0" on the "npm" registry.

## Possible Fix

Upgrade arcgis-webpack-plugin to use arcgis-js-api version 4.9.3

## Steps to Reproduce

1. Have a package.json that includes arcgis-webpack-plugin
2. Run an npm install (or yarn install)
3.
4.

## Context

Unable to develop using arcgis-webpack-plugin

## Your Environment

* Version used: 4.9.0
* node version: 10.12.0
* npm version: 6.4.1
* Operating System and version (desktop or mobile): Windows 10
* Link to your project if available:

**Comment by odoe** [comment]
I just tested this on Win10 with npm and yarn without issue.
Do you have .npmrc or .yarnrc file in your project? Have you updated any global npm settings?
Can you try installing that package manually using `npm i @dojo/framework@^3.0.1 --verbose` and see if that works?

**Comment by roemhildtg** [comment]
Even with npm I sometimes I have to type `npm install` twice to get all the packages. In 4.8, dojo wouldn't be downloaded until the second time.

**Comment by atdiff** [comment]
Apparently there is some setting in my npmrc that caused @dojo/framework to fail. I commented out the whole file and it worked fine.
