### ISSUE TITLE
Output library is mapped to dojo.js in development mode

### ISSUE THREAD

**Issue by sebastianfrey** [Esri/arcgis-webpack-plugin#28]
I don't know if this is a bug related to the arcgis-webpack-plugin, but in other setups without the arcgis-webpack-plugin the following error does not occur. 

## Description
When I launch my application with `webpack-dev-server`, the in `webpack.config.js` by `[output.library](https://webpack.js.org/configuration/output/#output-library)` defined variable is mapped to `dojo.js` also known as the dojo loader.

## Expected Behavior
Actualy I would expect, that the via `output.library` conigured variable is mapped to the module exports of the via `[entry](https://webpack.js.org/configuration/entry-context/#entry)` configured main file.

This is my webpack configuration:

```js
module.exports = {
  context: __dirname,
  entry:   './src/index.js',
  output: {
    path: path.join(__dirname, "examples"),
    filename: "bundle.js",
    library: 'lib'
  },
  devtool: 'inline-source-map',
  devServer: {
    contentBase: './examples'
  },
  module: {
    rules: [
      {
        test: /\.(png)|(gif)|(svg)|(woff)|(eot)|(ttf)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 100000
            }
          }
        ]
      },
      {
        test: /\.js/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/env'],
            plugins: [
              require("@babel/plugin-proposal-class-properties"),
              require("@babel/plugin-proposal-object-rest-spread"),
              require("@babel/plugin-syntax-dynamic-import"),
              require("@babel/plugin-transform-modules-umd")
            ]
          }
        }
      },
      {
        test: /\.css/,
        use: [
          { loader: "style-loader" },
          { loader: "css-loader" }
        ]
      }
    ]
  },
  plugins: [
    new ArcGISPlugin(),
    new HtmlWebPackPlugin({
      inject: true,
      chunksSortMode: 'none',
      template: 'examples/index.html'
    })
  ],
  externals: [
    (context, request, callback) => {
      if (/pe-wasm$/.test(request)) {
        return callback(null, "amd " + request);
      }
      callback();
    }
  ],
  node: {
    process: false,
    global: false
  }
};
```

This is how my `src/index.js` looks like.

```js
export { default as MyModule } from './MyModule';
```

Then in a simple HTML page served by `webpack-dev-server`, the from webpack created bundle is included as script tag. After that a second script tag is placed, which executes some JS, which just tries to access the exported module of my `index.js`.

index.html
```html
<script src="./bundle.js"></script>
<script>
  const myModuleInstance = new lib.MyModule(); // Fails with "lib.MyModule is not a constructor"
</script>
```
The webpack-dev-server is started with the following command:

`webpack-dev-server --mode development --open --port 5002`

## Context
I try to build an API, which is built on top of the ArcGIS JS API 4.

## Your Environment
* Version used: 4.8.1
* Browser Name and version:  All Browsers
* Operating System and version (desktop or mobile):  Ubuntu 18.04
* Link to your project if available: -

**Comment by valeviolin** [comment]
Did this get fixed for you @sebastianfrey ?  Still having the issue. Even with the @dojo-webpack-plugin-sample

**Comment by sebastianfrey** [comment]
@valeviolin Unfortunately this issue occurred during a student project and since this issue was only a beauty flaw for my task, I did not dig down any deeper into this. Sry about that.

I dont't know if this helps you, but if i remember correctly, the issue occurred only in development mode.
