### ISSUE TITLE
 ReferenceError: React is not defined

### ISSUE THREAD

**Issue by fuhidev** [Esri/arcgis-webpack-plugin#3]
webpack:///./node_modules/arcgis-js-api/widgets/Attribution.tsx?:47 Uncaught (in promise) ReferenceError: React is not defined
    at Object.Attribution.render (webpack:///./node_modules/arcgis-js-api/widgets/Attribution.tsx?:47)

**Comment by odoe** [comment]
What does your webpack config look like? Link to a sample project to reproduce?

Are you using the demo project here? https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo

Some more information please.

**Comment by Aiooioo** [comment]
Yes, i have got this same error.

I cloned the demo app from the above url.

By the way, there is another error in the demo app's webpack config file. The plugin package's name is "@arcgis/webpack-plugin" now, but it remains "arcgis-webpack-plugin"

**Comment by odoe** [comment]
Thanks @fuhidev and @Aiooioo!

Figured it out, there was a typo in the `.npmignore` of the `arcgis-js-api` that was not properly ignoring the `.tsx` files.

If you upgrade to `4.7.1` of the `@arcgis/webpack-plugin`, it should work now, I just double tested it again.

Thanks!

**Comment by fuhidev** [comment]
Thanks @odoe

The project is build success

**Comment by Aiooioo** [comment]
That works! Thank u.
