### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by atdiff** [Esri/arcgis-webpack-plugin#31]
## Description

When running webpack with the arcgis-webpack-plugin and the webpack-deep-scope-analysis-plugin, I encounter a "JavaScript heap out of memory" error.  If I comment out the use of the arcgis-webpack-plugin, it works fine.

```
[10640:0000020CC46D93B0]    87515 ms: Scavenge 1260.1 (1349.9) -> 1259.5 (1355.4) MB, 7.6 / 0.0 ms  (average mu = 0.168, current mu = 0.158) allocation failure
[10640:0000020CC46D93B0]    87670 ms: Scavenge 1263.4 (1355.4) -> 1263.2 (1355.4) MB, 7.4 / 0.0 ms  (average mu = 0.168, current mu = 0.158) allocation failure
[10640:0000020CC46D93B0]    87689 ms: Scavenge 1263.4 (1355.4) -> 1262.7 (1367.4) MB, 10.8 / 0.0 ms  (average mu = 0.168, current mu = 0.158) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000003A7C0F5C5C1]
Security context: 0x0056cb71e6e1 <JSObject>
    1: _addListener(aka _addListener) [000003FBDD61D4E9] [events.js:~193] [pc=000003A7C22223EC](this=0x02ea374026f1 <undefined>,target=0x0090982075e1 <Gzip map = 000002DD35A44BF9>,type=0x0056cb73ce89 <String[3]: end>,listener=0x009098207d21 <JSBoundFunction (BoundTargetFunction 000003FBDD61D529)>,prepend=0x02ea374029a1 <false>)
    2: constructor(aka Zlib)...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF66FDFACB5
 2: 00007FF66FDD44E6
 3: 00007FF66FDD4EF0
 4: 00007FF6700647FE
 5: 00007FF67006472F
 6: 00007FF670598964
 7: 00007FF67058F0F2
 8: 00007FF67058D68C
 9: 00007FF67058BFB7
10: 00007FF6703B5E74
11: 00007FF6701D8427
12: 000003A7C0F5C5C1
```

## Expected Behavior

The build should succeed and the bundle size should decrease

## Actual Behavior

An error occurs.

## Steps to Reproduce

1. Follow the usage instructions of the webpack-deep-scope-analysis-plugin - https://github.com/vincentdchan/webpack-deep-scope-analysis-plugin#usage

## Context

Attempting to use webpack-deep-scope-analysis-plugin with the project for better tree-shaking and improved bundle size.

## Your Environment

* Version used: 4.9.0
* Operating System and version (desktop or mobile): Windows 10
* Node: 10.12.0
* npm: 6.4.1

**Comment by atdiff** [comment]
Also getting similar error when using the basic webpack ProfilingPlugin - https://webpack.js.org/plugins/profiling-plugin/

**Comment by odoe** [comment]
I don't think it's going to work based on this part from the doc

> Notice: the plugin only works for import and export syntax module. If your code are transpiled to module.export and require syntax, the analyzer can't work correctly.

The JSAPI source is using the `require` syntax, so that might be part of the problem.
