### ISSUE TITLE
Is `transpileOnly: true` required to use this plugin?

### ISSUE THREAD

**Issue by wlindner** [Esri/arcgis-webpack-plugin#33]
Is the `transpileOnly` option required in order to use the arcgis-webpack-plugin? The sample linked to in the README has the `transpileOnly` option set to true for the `ts-loader` webpack loader. This is the example I'm following: https://github.com/Esri/jsapi-resources/blob/master/4.x/webpack/demo/webpack.config.js#L32

I did not have any typescript errors before using this plugin. When I added the ArcGIS plugin I had to change my `tsconfig.json` to compile `amd` modules instead of `esnext`, like this line: https://github.com/Esri/jsapi-resources/blob/master/4.x/webpack/demo/tsconfig.json#L3. Now, when I remove the `transpileOnly` option for the `ts-loader` I get a ton of new Typescript errors like `TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.` I don't think these errors are valid, because I didn't have them before adding this plugin.

## Context

I was trying to build a webapp with an ArcGIS map and typescript support, but it seems like I have to disable the typescript type checking in order to use this plugin. Is that the case?

**Comment by odoe** [comment]
You don't need to, but any little errors like implicit any's will stop the build. You could update your tsconfig to not worry about those `"noImplicitAny": false,`

**Comment by wlindner** [comment]
Ok, that makes sense. It's still odd to me that these typescript errors began after changing the typescript module output to `amd`. Is it necessary to change the typescript module output to `amd` in order to use the `arcgis-webpack-plugin` like in this example (https://github.com/Esri/jsapi-resources/blob/master/4.x/webpack/demo/tsconfig.json#L3)? I found that building the app with module output set to `es6` gets rid of my typescript errors, but causes issues similar to #22. This bug prevents workers from loading correctly, but the map still works, so I will probably keep using module output `es6` and `transpileOnly` set to `false` until the bug that #22 refers to is fixed. Do you foresee any issues with that configuration with this plugin?

**Comment by odoe** [comment]
The output of the compiler ts or babel needs to be amd as we pass the amd modules to the dojo plugin, as it is the dojo plugin that process the amd modules and passes them back into the webpack build. That will not change.

**Comment by odoe** [comment]
no plans for the near future
