### ISSUE TITLE
Bug with search with featureLayer source : "view:no-layerview-for-layer"

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-webpack-plugin#34]
## Description
When using search with sources coming from FeatureLayer, search operation (once result is selected), it fails to draw the graphic result and returns an error "view:no-layerview-for-layer"

## Expected Behavior
It should display the result graphic from search without any error in the console.

## Actual Behavior
Highlighted result graphic missing and an error is logged (twice)

## Possible Fix
It runs fine without the webpack build:
https://developers.arcgis.com/javascript/latest/sample-code/widgets-search-multiplesource/index.html

## Steps to Reproduce
1. Create a new app with arcgis-cli : "arcgis create <name>"
2. Define sources in the search:
```js
const search = new Search({ 
      view: this.view,
      sources: [{
        featureLayer: {
          url: "https://services.arcgis.com/V6ZHFr6zdgNZuVG0/arcgis/rest/services/CongressionalDistricts/FeatureServer/0",
        },
        searchFields: ["DISTRICTID"],
        displayField: "DISTRICTID",
        exactMatch: false,
        outFields: ["DISTRICTID", "NAME", "PARTY"],
        name: "Congressional Districts",
        placeholder: "example: 3708",
      }]
    });
```
3. Search for a congessional disctrict and select result
4. Map zooms to result but no graphic is displayed and an error "view:no-layerview-for-layer" is logged in the console

## Your Environment

* Version used: @arcgis/webpack-plugin@~4.9.0
* Browser Name and version: Chrome

**Comment by Biboba** [comment]
Hello,

Any idea where could the problem come from ?
Do you think it comes from the webpack build ? 
I can't figure out what is wrong... Any hints would be greatly appreciated.

Many thanks for your help on this issue

**Comment by odoe** [comment]
No clues as of yet. I can't track down what is causing this issue. Will require more time.

**Comment by Biboba** [comment]
Thanks for the reply.
Glad to know that you can reproduce the issue on your side as well.

**Comment by odoe** [comment]
Sounds good
