### ISSUE TITLE
Worker Path incorrect while using React Router

### ISSUE THREAD

**Issue by wlindner** [Esri/arcgis-webpack-plugin#35]
Our app loads ArcGIS when we open it from the root route: `/`. Our app also supports additional routes `/foo/5`. If we open the app from a route other than the root, we get console errors about workers not loading properly because the worker is getting loaded from `/foo/arcgis-js-api/core/workers/worker.js`. How can we configure this webpack plugin to load those files from the root instead of a relative path that gets a 404 when we load the page from a route?

## Expected Behavior

Accessing our app from a route should load additional libraries properly.

## Actual Behavior

The libraries load from a URL that includes the route, which results in a 404.

**Comment by odoe** [comment]
Can you try `HashRouter` and see if that works. I'm using that in a current application and it works fine.

**Comment by wlindner** [comment]
No, I am not able to replace the router in our application. We have been using the React Esri Loader, but were interested in switching to the Webpack plugin instead since the Esri Loader uses such a non-standard approach for loading libraries. We have had too many issues trying to integrate the webpack plugin into our application and will no longer attempt to use it.
