### ISSUE TITLE
calcite errors - dont load icons

### ISSUE THREAD

**Issue by TokarAndrii** [Esri/arcgis-webpack-plugin#36]
### calcite errors
Hi I am trying arcgis-webpack-plugin and made clone app https://github.com/odoe/jsapi-webpack
But when i just changed react component from SceneView to MapView and add a simple Map as const ```
webmap = new WebMap({
  portalItem: {

    id: "15fa6c0f93704219a09f1c527616afdb" //simple base map openstreet
  }
});
```
i got  errors - none  icon has been loaded:
![calcite_error](https://user-images.githubusercontent.com/13175855/48845164-7baaa300-eda4-11e8-8e3f-3d15f09fd31a.png)

i dont make any changes at webpack.config.js - just install all dependencies


Also it appears  - index.bundle.js:186 ReferenceError: __WEBPACK_EXTERNAL_MODULE__support_pe_wasm__ is not defined
    at eval (pe-wasm":1)
    at Object../support/pe-wasm (index.bundle.js:19588)
    at __webpack_require__ (index.bundle.js:64)
    at eval (pe.js:25)

and as discribed at  https://github.com/Esri/arcgis-webpack-plugin/issues/8  dont help. after reloading app crashed

Have You any ideas how to fix it?

**Comment by TokarAndrii** [comment]
when i just removed node_modules and package-lock.json and run npm install -  icons appears but  still present error 
index.bundle.js:186 ReferenceError: __WEBPACK_EXTERNAL_MODULE__support_pe_wasm__ is not defined
Uncaught (in promise) ReferenceError: __WEBPACK_EXTERNAL_MODULE__support_pe_wasm__ is not defined

**Comment by odoe** [comment]
There have been some updates to the dependencies we use in our plugin and everything seems work fine, I can't repro.

You can test in this app here which is an updated version of the jsapi-webpack app.
https://github.com/odoe/jsapi-react

Thanks!

**Comment by TokarAndrii** [comment]
Thanks for the answer, yes I reset all dependencies and all started to
work  correctly


ср, 27 лют. 2019 о 22:26 Rene Rubalcava <notifications@github.com> пише:
