### ISSUE TITLE
Arcgis js api 4.9 + boostrap 4 -- jQuery: Module not found

### ISSUE THREAD

**Issue by diminglei** [Esri/arcgis-webpack-plugin#37]
After added Arcgis Webpack plugin, I got Module not found: jquery
## Description
I used boostrap 4 and webpack, after added new ArcGISPlugin() to webpack config. got Module not found: jquery. When removed ArcGISPlugin from webpack, the page is loaded properly.
## Expected Behavior

The page should be loaded properly.
## Actual Behavior

Got Module not found: jquery
## Steps to Reproduce

1.
2.
3.
4.

## Context

Yes, I just want to setup a Arcgis + webpack app
## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by Biboba** [comment]
https://community.esri.com/thread/225425-arcgis-webpack-plugin-doesnt-work-with-bootstrap-4

**Comment by diminglei** [comment]
Hi Biboba, here's my webpack config:
module.exports = {
target: 'web', // <=== can be omitted as default is 'web'
mode: 'development',
entry: {
main: ["./css/aqhi.scss", "./Scripts/main.ts"]
},
output: {
path: path.resolve(__dirname, 'dist')
},
resolve: {
modules: [
path.resolve(__dirname, "/Scripts"),
path.resolve(__dirname, "node_modules/")
],
extensions: ['.webpack.js', '.web.js', '.ts', '.tsx', '.js'],
alias: {
// Force all modules to use the same jquery version.
'jquery': path.join(__dirname, 'node_modules/jquery/src/jquery'),
'moment': path.join(__dirname, 'node_modules/moment/moment.js'),
'datetimepicker': path.join(__dirname, 'node_modules/tempusdominus-bootstrap-4/build/js/tempusdominus-bootstrap-4.min.js')
}
},
plugins: [
new CleanWebpackPlugin(["dist"]),
new webpack.ProvidePlugin({
$: "jquery",
jQuery: "jquery",
"jquery": "jquery",
"windows.jQuery": "jquery",
moment: "moment"
}),
new ArcGISPlugin(),
],
module: {
rules: [{
test: /\.s?css$/,
use: [{
// Adds CSS to the DOM by injecting a `<style>` tag
loader: 'style-loader'
},
{
// Interprets `@import` and `url()` like `import/require()` and will resolve them
loader: 'css-loader'
},
{
// Loader for webpack to process CSS with PostCSS
loader: 'postcss-loader',
options: {
plugins: function() {
return [
require('autoprefixer')
];
}
}
},
{
// Loads a SASS/SCSS file and compiles it to CSS
loader: 'sass-loader'
}
]
},
{
test: /\.tsx?$/,
loader: "ts-loader",
options: {
transpileOnly: true
}
},
{
test: /\.(png|jpg|ttf|eot|woff|woff2|svg)$/,
loader: 'url-loader?limit=10000'
},
{
test: /\.(ttf|eot|svg)(\?[\s\S]+)?$/,
use: 'file-loader',
},
{
test: /\.(jpe?g|png|gif|svg)$/i,
use: [
'file-loader?name=images/[name].[ext]',
'image-webpack-loader?bypassOnDebug'
]
},
{ // font-awesome
test: /font-awesome\.config\.js/,
use: [{
loader: 'style-loader'
},
{
loader: 'font-awesome-loader'
}
]
}
]
}
};

**Comment by diminglei** [comment]
Thanks Rene, I tried useDefaultAssetLoaders in my project not working, I will check your samples.
Much appreciated!
