### ISSUE TITLE
Install fail with yarn ,error: unexpected end of file

### ISSUE THREAD

**Issue by chunjil** [Esri/arcgis-webpack-plugin#38]
yarn add @arcgis/webpack-plugin

error: An unexpected error occurred: "https://codeload.github.com/Esri/dojo-util/tar.gz/b780eb59dc4deab51af2e1d0715b222b7be5a434: unexpected end of file".

yarn version:1.12.3

npm install success~

**Comment by odoe** [comment]
I'm not seeing this with yarn 1.13.0. Can you try with the latest version?

**Comment by odoe** [comment]
This issue looks to be resolved with latest versions of yarn and plugin. If it comes up again, let me know, thanks!

**Comment by nayinianJQ** [comment]
Hi, it happen again on yarn 1.22.4
![image](https://user-images.githubusercontent.com/25129445/87223720-be722200-c3b1-11ea-8b32-c7a4ce5b9393.png)
