### ISSUE TITLE
not working with calcite-maps

### ISSUE THREAD

**Issue by diminglei** [Esri/arcgis-webpack-plugin#40]
arcgis-webpack-plugin cannot load calcite-maps
## Description
I added calcite map packages to config:

{
      name: "bootstrap",
      location: "https://esri.github.io/calcite-maps/dist/vendor/dojo-bootstrap"
    },
    {
      name: "calcite-maps",
      location: "https://esri.github.io/calcite-maps/dist/js/dojo"
    },

## Expected Behavior
calcite-maps modules should be loaded

## Actual Behavior
calcite-maps modules are not loaded

## Steps to Reproduce
1. download code from https://github.com/odoe/jsapi-bootstrap
2. modify  jsapi-bootstrap/src/config.ts, add calcite-maps modules:
{
      name: "bootstrap",
      location: "https://esri.github.io/calcite-maps/dist/vendor/dojo-bootstrap"
    },
    {
      name: "calcite-maps",
      location: "https://esri.github.io/calcite-maps/dist/js/dojo"
    },
3. referring calcite-maps in my code:
import Collapse from "bootstrap/Collapse";
import Dropdown from "bootstrap/Dropdown";
import CalciteMaps from "calcite-maps/calcitemaps-v0.10";
import CalciteMapArcGISSupport from "calcite-maps/calcitemaps-arcgis-support-v0.10";

4. 
runtime error: cannot find calcite-maps

[esriConfig.zip](https://github.com/Esri/arcgis-webpack-plugin/files/2866998/esriConfig.zip)

## Context
This issue is show stopper, I need CalciteMaps working with arcgis-webpack-plugin

## Your Environment
Node.js

**Comment by odoe** [comment]
That configuration is only for the workers in the ArcGIS API for JavaScript, they do not map libraries into your application. You need to install `calcite-maps` to use it.
https://github.com/Esri/calcite-maps

`npm install --save calcite-maps`

**Comment by diminglei** [comment]
Thanks, I raised an issue there: https://github.com/Esri/calcite-maps/issues/222

**Comment by crackernutter** [comment]
Seems like no resolution on this?  I keep getting a "define is not defined" error when trying to load calcite-maps modules and dojo-bootstrap modules
