### ISSUE TITLE
Unit testing with Angular and arcgis?

### ISSUE THREAD

**Issue by atdiff** [Esri/arcgis-webpack-plugin#42]
I'm using the arcgis-webpack-plugin for an Angular app. The app works great and the component renders a map. For the unit testing, though, I'm uncertain what I need to do and not finding any examples. I'm using Jest as the testing framework with jest-preset-angular. The tests are ran individually/independently and not against the bundled code. So when testing the Angular component, it doesn't recognize the esri code and I get "Cannot find module 'esri/Map'".
How should unit testing be done when utilizing arcgis-webpack-plugin to pull in the Esri pieces? If using esri-loader, it seems like the unit testing would be easier, but I'd prefer to go the plugin route for now.

## Your Environment

* Version used: 4.10.4
* Operating System and version (desktop or mobile): Windows 10

**Comment by atdiff** [comment]
For the moment, I've added the following section to my jest config file.

```
moduleNameMapper = {
    'esri/Map': '<rootDir>/src/test/MockEsri.ts',
    'esri/views/MapView': '<rootDir>/src/test/MockEsri.ts',
    'esri/Graphic': '<rootDir>/src/test/MockEsri.ts',
    'esri/symbols/SimpleFillSymbol': '<rootDir>/src/test/MockEsri.ts',
    'esri/symbols/SimpleMarkerSymbol': '<rootDir>/src/test/MockEsri.ts',
    'esri/geometry/Polygon': '<rootDir>/src/test/MockEsri.ts',
    'esri/geometry/Multipoint': '<rootDir>/src/test/MockEsri.ts'
}```

And the MockEsri.ts file just contains an empty object. So essentially just mocking the esri stuff since I'm not testing the logic around that currently.

**Comment by LukashenkoEvgeniy** [comment]
You can simplify:

> moduleNameMapper = {
>     '(esri|dojo|dojox)(.*)$':  '<rootDir>/src/test/MockEsri.ts'
> }
