### ISSUE TITLE
JSX typing error in TypeScript project with React

### ISSUE THREAD

**Issue by JulianKowalczuk** [Esri/arcgis-webpack-plugin#43]
## Expected Behavior
Ability to use React along with plugin.

## Actual Behavior
Error breaks typing of JSX elements. It requires following line:
```js
import { tsx } from "esri/widgets/support/widget";
```
and ignores importing React module.

## Possible Fix
arcgis-js-api contains maquette and maquette-jsx packages. Their global type declarations of JSX probably breaks everything. Since I'm not interested in using maquette, it would be nice to get rid of it.

## Steps to Reproduce
1. Download demo from link below.
https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo
2. Install react and react-dom packages and @types ones.
3. Jump into any *.tsx file and see error.

## Context
It doesn't allow me to use Your Esri client solution with React in one project...

## Your Environment
* Version used: ~4.10.5
* Browser Name and version: Chrome 73.0.3683.86
* Operating System and version (desktop or mobile): Windows 10
* Link to your project if available: -

**Comment by odoe** [comment]
You may need to update your tsconfig.json.

Look at this sample with TS/React and the webpack plugin.
https://github.com/odoe/jsapi-react-template

Your [tsconfig](https://github.com/odoe/jsapi-react-template/blob/master/tsconfig.json) might have the following.

```json
"jsxFactory": "tsx",
``` 

If you do, remove it and everything should just work.

**Comment by JulianKowalczuk** [comment]
The funny thing is I found out it about 30min after posting issue :smile: 
I was using Your demo for JS (with Babel) solution, but didn't realize that You have similar project.
Anyway - thanks for reply! Now I can hustle with project.
