### ISSUE TITLE
Failed to fetch pe-wasm

### ISSUE THREAD

**Issue by tgeorges** [Esri/arcgis-webpack-plugin#44]
Hi @odoe, 
I have a not so special case where main code is loaded from  a webserver port 80, and ArcGIS API is loaded from this server (for example webpack dev server) on port 8080.
In this case, ArcGIS API try to load pe asm on webserver with port 80 : it seams that asm loader in module node_modules/arcgis-js-api/geometry/support/pe-wasm.js does not use dojo config base url to fetch this module.
Do you confirm it ? Does it make sense for you to fix it in the API ?

Without that we cannot use that feature of the api :-(

Thanks

_Originally posted by @tgeorges in https://github.com/Esri/arcgis-webpack-plugin/issues/8#issuecomment-477917489_

**Comment by rhys-d** [comment]
I am getting this Chrome console message when trying to use the out-of-the-box Measure widget with a non-web-mercator basemap: "Uncaught (in promise) ReferenceError: __WEBPACK_EXTERNAL_MODULE__support_pe_wasm__ is not defined" - Could this also be related?
