### ISSUE TITLE
Getting it to work with Vue

### ISSUE THREAD

**Issue by stanleyck** [Esri/arcgis-webpack-plugin#45]
Hi, thanks for this nice plugin! 

It would be great if you could add documentation for how we can use the plugin in a Vue setup.

**Comment by odoe** [comment]
Please see the latest resource updates with a sample using the webpack plugin with the vue-cli https://github.com/Esri/jsapi-resources/tree/master/frameworks/vue#arcgis-webpack-vue-calcite

Thanks!
