### ISSUE TITLE
ColorSlider's "xAvg.svg" file is not included

### ISSUE THREAD

**Issue by ReneU** [Esri/arcgis-webpack-plugin#48]
ColorSlider's "xAvg.svg" file is not included

## Description
When using the ColorSlider module to build a widget similar to the [API Sample](https://developers.arcgis.com/javascript/latest/sample-code/visualization-sm-color/index.html) the svg image that indicates the average on the histogram can't be loaded as it is not included.

## Expected Behavior
Average-icon file should be loaded like any other theme-related svg

## Actual Behavior
`GET http://localhost:8080/arcgis-js-api/widgets/RendererSlider/xAvg.svg 404 (Not Found)`

## Possible Fix
I'm not an expert but as the path is not covered by any of the existing sections of the CopyWebpackPlugin, I guess it should be sufficient to add this snippet to it:
`
{
      context: "node_modules",
      from: "arcgis-js-api/widgets/RendererSlider/xAvg.svg"
},
`

## Steps to Reproduce
I could build a minimal sample with the [arcgis-js-cli](https://github.com/Esri/arcgis-js-cli) if required. Otherwise it's sufficient to include the ColorSlider in your application.

## Context
I'm using the [arcgis-js-cli](https://github.com/Esri/arcgis-js-cli). The error occurs no matter if using dev-mode or production-mode

## Your Environment
* Version used: 4.11.0
* Browser Name and version: Google Chrome Version 74.0.3729.169
* Operating System and version (desktop or mobile): Windows 10 Enterprise (desktop)

**Comment by odoe** [comment]
This is now fixed in latest release. Thanks!
