### ISSUE TITLE
Documentation: mini-css-extract-plugin has webpack 4 dependency

### ISSUE THREAD

**Issue by andygup** [Esri/arcgis-webpack-plugin#5]
Recommend adding a small note [here](mini-css-extract-plugin) that `mini-css-extract-plugin` has a webpack 4 dependency. I'm not sure what an equivalent webpack 3 alternative is, but if you know it might be helpful to suggest it in the doc, as well...

Reference:
https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by odoe** [comment]
Updated via #6

**Comment by tonylikestoburns** [comment]
Thanks
