### ISSUE TITLE
why localization Arcgis API for js in @arcgis/webpack-plugin not working

### ISSUE THREAD

**Issue by dxiuxiu** [Esri/arcgis-webpack-plugin#50]
my  environment   "@arcgis/webpack-plugin": "^4.11.0", "webpack": "^4.33.0",
i use @arcgis/webpack-plugin for asrcgis api for js work with webpack,At first all was well，but when i want to set localization like this

`
<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script>
		var dojoConfig = {
			locale: 'zh-cn',
                       parseOnLoad: true
    }
  </script>
  <title>
    Webpack App
  </title>
<link href="style/index.02752355b6237e15ecc5.css" rel="stylesheet"></head>

<body>
  <div id="root"></div>
<script type="text/javascript" src="static/js/index.3a6d182a5f7f766e2f35.js"></script></body>
</html>
`
 but it is not working ,i refer to this https://developers.arcgis.com/javascript/latest/guide/localization/ and i use like this in many place include Arcgis api for js v4.11 with esri-loader

this is my code in gitHub https://github.com/dxiuxiu/arcgis-webpack-ArcGISPlugin.git

**Comment by odoe** [comment]
You don't define locales via a `dojoConfig` with the plugin.

The ArcGIS Webpack plugin provides a `locales` option that passes the array of strings to the dojo-webpack-plugin.
https://github.com/Esri/arcgis-webpack-plugin#options

You can refer to the dojo-webpack-plugin for details on how to use it.
https://github.com/OpenNTF/dojo-webpack-plugin#locales

**Comment by dxiuxiu** [comment]
en.....,can you give me some core codes for this function,becuse i was tried by my self and it not working too, my add code only like below
' new ArcGISPlugin({
      useDefaultAssetLoaders: false,
      locales : ['zh-cn'] // my add config
    }),'
,and i read you give me documents (https://github.com/Esri/arcgis-webpack-plugin#options  https://github.com/OpenNTF/dojo-webpack-plugin#locales)，i think this config only decide Which language packages output to dist not what language was use in project。

my english is not good ,I pray i can make it clear  what i want to say

**Comment by odoe** [comment]
@dxiuxiu if you do not set any `locales`, leave it blank. Your application will have all the locales available when it runs. The browser will determine the locales to load in your application based on location or browser settings. You should not have to change anything.

Is that not working as you expect?

**Comment by dxiuxiu** [comment]
thank you very much,i resolve my problem.now i can use my language as you say。

To my great confusion, I don't know why I was wrong before, I didn't seem to change any code... so strange!!!

Maybe I have too many questions,because i find another one is when  setting ArcGISPlugin like this 
```
new ArcGISPlugin({
      useDefaultAssetLoaders: false,
      locales : ['zh-cn']
}),
```

or 
```
new ArcGISPlugin({
      useDefaultAssetLoaders: false,
}),
```
the build result in  folder dojo/nls look like same,when i set  locales : ['zh-cn'] ,it should only have  language file named dojo_zh-cn.js but there have all language files like next:

![ArcgisPlugin](https://user-images.githubusercontent.com/37434808/60408058-e8660580-9bef-11e9-98c6-fab8e49f0edb.png)

**Comment by LukashenkoEvgeniy** [comment]
Hello, I have problems with using arcgis arcgis-webpack-plugin. This is fragment of webpack config
```
            new ArcGISPlugin({
                useDefaultAssetLoaders: false,
                locales: ['uk'],
                root: 'node_modules'
            }),
....
```
When I set up **uk** lang arcgis use default (en) lang,
When I set up **ru** lang, plugin use russian lang

Did you test plugin with new languages and how I can solve this proplem? Its very important.

Thank you!

**Comment by odoe** [comment]
@LukashenkoEvgeniy  Do you have a sample project? I just tried this with and set my browser to display in `uk` and was able to see the following result.

![Screen Shot 2019-07-02 at 1 33 02 PM](https://user-images.githubusercontent.com/206462/60544640-0bff7d80-9cce-11e9-83e0-a22f8a4c6363.png)

It might help to see if there is something else interfering with the build, thanks!

**Comment by LukashenkoEvgeniy** [comment]
@odoe, which browser you use? When i run project in chrome locale use default value en, in firefox locale which i set in locale property.

Firefox
![image](https://user-images.githubusercontent.com/17275749/60789682-54081f80-a168-11e9-822d-b920eaafc39d.png)

Chrome
![image](https://user-images.githubusercontent.com/17275749/60789722-71d58480-a168-11e9-9c2e-4dbcb7d89890.png)

**Comment by LukashenkoEvgeniy** [comment]
I see that dojo use locale from window.navigator.language and set as default if it exist in i18n.
Do you know way set up language in dojo and disable tacking it from browser?

**Comment by MichalisM** [comment]
> I see that dojo use locale from window.navigator.language and set as default if it exist in i18n.
> Do you know way set up language in dojo and disable tacking it from browser?
> 
> When we define ArcGISPlugin we just set up whick locales will be included into result build

@LukashenkoEvgeniy, the way I have found is by loading our own config file at the ArcGISPlugin in webpack.config.js and make it run not only during build but also at runtime. Here is the change in the webpack.config.js:

```
new ArcGISPlugin({
     loaderConfig: require.resolve("./src/loaderConfig")
})
```

and the loaderConfig.js file looks like that (you can change the selectedLanguage as you want):
```
var selectedLanguage = "en-US";

function getConfig(env) {

  var loaderConfig = {
    baseUrl: ".",
    locale: selectedLanguage,
    packages: [
      {
        name: "esri",
        location: env.root + "/arcgis-js-api",
        main: "kernel"
      },
      {
        name: "@dojo",
        location: env.root + "/@dojo",
        lib: "."
      },
      {
        name: "cldrjs",
        location: env.root + "/cldrjs",
        main: "dist/cldr"
      },
      {
        name: "globalize",
        location: env.root + "/globalize",
        main: "dist/globalize"
      },
      {
        name: "tslib",
        location: env.root + "/tslib",
        main: "tslib"
      },
      {
        name: "moment",
        location: env.root + "/moment",
        lib: "."
      },
      {
        name: "dojo",
        location: env.root + "/dojo",
        lib: "."
      },
      {
        name: "dijit",
        location: env.root + "/dijit",
        lib: "."
      },
      {
        name: "dojox",
        location: env.root + "/dojox",
        lib: "."
      },
      {
        name: "dstore",
        location: env.root + "/dojo-dstore",
        lib: "."
      },
      {
        name: "maquette",
        location: env.root + "/maquette",
        main: "dist/maquette.umd",
        resourceTags: {
          miniExclude: function (filename, mid) {
            return (
              mid.indexOf("/polyfills/") > -1 ||
              (mid.indexOf("/dist/") > -1 &&
                filename.indexOf(".umd.js") === -1)
            );
          }
        }
      },
      {
        name: "maquette-css-transitions",
        location: env.root + "/maquette-css-transitions",
        main: "dist/maquette-css-transitions.umd",
        resourceTags: {
          miniExclude: function (filename, mid) {
            return (
              mid.indexOf("/dist/") > -1 && filename.indexOf(".umd.js") === -1
            );
          }
        }
      },
      {
        name: "maquette-jsx",
        location: env.root + "/maquette-jsx",
        main: "dist/maquette-jsx.umd",
        resourceTags: {
          miniExclude: function (filename, mid) {
            return (
              mid.indexOf("/dist/") > -1 && filename.indexOf(".umd.js") === -1
            );
          }
        }
      }
    ],
    map: {
      globalize: {
        cldr: "cldrjs/dist/cldr",
        "cldr/event": "cldrjs/dist/cldr/event",
        "cldr/supplemental": "cldrjs/dist/cldr/supplemental",
        "cldr/unresolved": "cldrjs/dist/cldr/unresolved"
      }
    },
    async: true,
    has: {
      "dojo-config-api": 0, // Don't need the config API code in the embedded Dojo loader
      "esri-promise-compatibility": 1,
      "esri-webpack": 1
    }
  };

  return loaderConfig;
}

if (typeof module !== "undefined" && module) {
  module.exports = getConfig
} 

```
Hope it is what you are looking for.

**Comment by odoe** [comment]
I see what you're tying to do now. I'll add this as an option under `features` since it impacts the dojo build output. This will go out in the next release of the plugin. Thanks!

**Comment by besLisbeth** [comment]
Hi, @odoe. I'm still facing a problem of @LukashenkoEvgeniy. Is it still planned to be implemented?

**Comment by odoe** [comment]
I need to test this further, as our localization has changed for 4.16. Might require an updated configuration.

**Comment by odoe** [comment]
Please see [this issue](https://github.com/Esri/arcgis-webpack-plugin/issues/89). Localization is now handled differently in the ArcGIS API for JavaScript and is not defined by the plugin anymore. Our localization is all dynamic and no strings are baked into built code. Although if you are using some Dojo bits in your app, it should still apply there.

I am currently considering if a locale defined in the plugin would filter the the copied localization files, but nothing is yet implemented.

Thanks
