### ISSUE TITLE
No solution with dynamic Dojo/Require 

### ISSUE THREAD

**Issue by dvbouali** [Esri/arcgis-webpack-plugin#52]
Hello everybody, i hope you will see my issue.

I have a very big problem with the common problem (DYNAMIC REQUIRE) but now it’s about dojo require.
i have tried the code splitting webpack, not working
the lazy loading not working
i have tried libraryTarget :’amd’ same thing .. 

here is my code 

in the config i use the simple configuration of arcgisPlugin

webpack.config.js
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const ArcGISPlugin = require('@arcgis/webpack-plugin');


module.exports = {
 entry: {
   index: './src/js/importing.js'
 },
 output: {
   filename: '[name].bundle.js',
   path: path.resolve(__dirname, '../dist')
 },
 module: {
   rules: [
     {
       test: [/.js$/],
       exclude: /(node_modules)/,
       use: {
         loader: 'babel-loader',
         options: {
           presets: ['@babel/preset-env']
         }
       }
     },
     {
       test: /\.html$/,
       use: [
         {
           loader: 'html-loader',
           options: { minimize: true }
         }
       ]
     },
     {
       test: [/.css$|.scss$/],
       use: [
         {
           loader: MiniCssExtractPlugin.loader
         },
         'css-loader',
         'sass-loader',
         'postcss-loader'
       ]
     },
     {
       test: /\.(png|jpg|gif|svg)$/,
       use: [
         {
           loader: 'file-loader',
           options: {
             name: '[name].[ext]',
             outputPath: 'assets/images'
           }
         }
       ]
     },
     {
       test: /\.(wsv|ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
       use: [
         {
           loader: 'file-loader',
           options: {
             name: 'build/[name].[ext]'
           }
         }
       ]
     },
     {
       test: /\.js$/,
       loader: 'dojo-webpack-loader',
       include: path.resolve(__dirname, '../dojo/')
     }
   ]
 },

 plugins: [
   new CleanWebpackPlugin(),
   new ArcGISPlugin({
     useDefaultAssetLoaders: false
   }),
   new MiniCssExtractPlugin({
     filename: 'style.[chunkhash].css'
   }),
   new HtmlWebpackPlugin({
     title: 'lifadmin',
     template: './src/index.html',
     chunksSortMode: 'none',
     minify: {
       removeComments: true,
       collapseWhitespace: false
     }
   }),
   new CopyWebpackPlugin([
     {
       from: './src/assets/images',
       to: 'assets/images'
     }
   ])

 ],

 resolve: {
   modules: [path.resolve(__dirname, '/src'), 'node_modules/'],
   extensions: ['.js', '.scss']
 },


 node: {
   process: false,
   global: false,
   fs : 'empty'
 }
};
```

here i’m importing the scss and the config arcgis and my main file application and calling the startup function

importing.js
```
define([
"./main",   
'./config/arcgisConfig',
'../scss/main.scss'], function (main) {
   main.startup();
});
```

here, i would like to create list of widgets for future configuration and importing each one in the (require dojo)

main.js
```
define(["require"], function (require) {

   return {

       startup: function () {
           this.initWidgets();
       },

       initWidgets: function () {
           let listWidgets = {
               menu:
               {
                   type: 'simple',
                   title: 'Example',
                   icon: '<i class="fas fa-pencil-alt"></i>',
                   widget: {
                       path: './exampleWidget'
                   }
               }
           };

           require([(listWidgets.menu.widget.path)], Widget => {
               let construction = new Widget();
           });
       },

   }
});
```

the widget with template simple div !

exampleWidget.js
```
define([
   'dojo/_base/declare',
   'dijit/_WidgetBase',
   'dijit/_TemplatedMixin',

 ], function(declare, _WidgetBase, _TemplatedMixin, ) {
   return declare([_WidgetBase, _TemplatedMixin], {
     templateString: '<div>Hello Widget</div>',
     startup() {
       this.inherited(arguments);
     }
   });
 });
 ```

i get this error

>Uncaught (in promise) Error: Module not found: src/js/exampleWidget
>   at findModule (index.bundle.js:167)
>  at contextRequire (index.bundle.js:193)
>    at result (index.bundle.js:108)
>    at eval (main.js:18)

how can i resolve this ?.. I just created a repo github for testing if you want 

##THE LINK
https://github.com/dvbouali/test-arcgis-webpack

**Comment by dvbouali** [comment]
i get this response from checkdumont after opened the same issue in dojo-webpack-plugin, and it give a good result at the moment i will close the issue, thank you

The issue here is that webpack cannot load unknown dependencies. The typical way for a dependency to become known is to encounter a 'require' statement using a string literal during the compilation. There may be other webpacky ways to do the same thing (e.g. the Dependency Injection Plugin), but I'm not familiar enough with them to suggest how to use them).

In your use case, if all of the dependencies used by your app are known at build time, then the easiest solution would be to make minor changes to initWidgets as follows:

       initWidgets: function () {
           let listWidgets = {
               menu:
               {
                   type: 'simple',
                   title: 'Example',
                   icon: '<i class="fas fa-pencil-alt"></i>',
                   widgetLoadFn: callback => require(['./exampleWidget'], callback);
               }
           };

           listWidgets.menu.widgetLoadFn(Widget => {
               let construction = new Widget();
           });
       },
If your dependencies are not known at build time, then webpack is likely not a good fit and you'd be better off sicking with the Dojo build tools.

Some folks have had success with using third-party AMD loaders (see #183). The main drawback with this is that any dependencies required by modules loaded this way will also be loaded by the third-party loader, resulting in duplication of modules that are common between your webpack build and the dynamically loaded modules.

**Comment by odoe** [comment]
Sorry, I was deep into Esri UC prep this past couple of week. But yes, require with expressions won't get picked up in webpack. We made lots of updates in our own codebase to avoid usage in this way.

One thing we do that might help is require with a promise. Something similar to what you are doing.

```js
const LoaderMap = {
  exampleWidget: () => new Promise(resolve => require(['./exampleWidget'], resolve))
};
```

We use this kind of pattern in some of our own modules.
