### ISSUE TITLE
@arcgis/webpack-plugin working with component library named antd report an error Can't resolve 'moment/main' in... 

### ISSUE THREAD

**Issue by dxiuxiu** [Esri/arcgis-webpack-plugin#53]
## Description
@arcgis/webpack-plugin working with component library named antd report an error Can't resolve 'moment/main' in... 

you can run my code https://github.com/dxiuxiu/arcgis-webpack-ArcGISPlugin to reappear this bug ,i try to remove webpack setting relatived to @arcgis/webpack-plugin this bug will disappear

webpack setting relatived to @arcgis/webpack-plugin 
```javascript
const ArcGISPlugin = require("@arcgis/webpack-plugin");
module.exports = {
  plugins: [
    new ArcGISPlugin({
      useDefaultAssetLoaders: false,
    }),
  ],
  externals: [
    (context, request, callback) => {
      if (/pe-wasm$/.test(request)) {
        return callback(null, "amd " + request);
      }
      callback();
    }
  ],
  node: {
    process: false,
    global: false
  }
}
```
or remove antd 

but i just want to use @arcgis/webpack-plugin with antd ,how can i do ?

this is very important and emergency ,i want use they to develop my project 。

**Comment by roemhildtg** [comment]
I have a project that uses Chart.js in it. When I bundle the project (which also uses arcgis plugin) I get this error also. Seems that `chart.js` requires moment and somewhere the arcgis plugin is remapping moment to `moment/main` perhaps?

**Comment by odoe** [comment]
We have to remap for our use of moment in the API. Mainly for proper locale loading. I'll look into seeing if there is a build way around this.

**Comment by ekrapfl** [comment]
I am also running into this and am interested in a workaround.  We use moment in our app currently, and we would like to use this plugin as well, but it appears that they do not work well together currently.

**Comment by martin-cernak** [comment]
Are there any plans for solving this?

**Comment by odoe** [comment]
I don't have a solid reproducible case other than using `chart.js` with time series.
I published a 4.14.2 that fixes it there.
https://github.com/Esri/arcgis-webpack-plugin/releases/tag/4.14.2

@roemhildtg can you verify it works in your case?
@dxiuxiu please verify in yours

**Comment by roemhildtg** [comment]
Can you update on npm @odoe ?

**Comment by odoe** [comment]
@roemhildtg https://www.npmjs.com/package/@arcgis/webpack-plugin/v/4.14.2

**Comment by roemhildtg** [comment]
Appears to work for me!
