### ISSUE TITLE
Project Compiles Twice

### ISSUE THREAD

**Issue by atdiff** [Esri/arcgis-webpack-plugin#54]
## Description

In projects that have arcgis-webpack-plugin, the code gets compiled twice when ran with webpack-dev-server. 
## Expected Behavior

The code should only compile once.
## Actual Behavior

Code is compiling twice (based on receiving two "Compiled successfully" messages) and longer build/serve process.
## Possible Fix

I'm wondering if this is more of a dojo-webpack-plugin side effect. When testing with their [demo project](https://github.com/OpenNTF/dojo-webpack-plugin-sample), the dual compilation occurs. But with projects without the webpack plugins for arcgis or dojo, it doesn't happen.
## Steps to Reproduce

1. Used the code from https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo
2. npm install
3. npm start
4. Note in the resulting output that there are two "Compiled successfully" messages

## Context

It's more of an annoyance than a big problem. Slows down the build. And when using bundle analysis and build notification plugins, it causes duplications of those tasks.
## Your Environment

* Version used: 4.11.0
* Browser Name and version: Chrome Version 75.0.3770.100 (64-bit)
* Operating System and version (desktop or mobile): Windows 10
* Link to your project if available: https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo

**Comment by odoe** [comment]
Should be fixed in latest releases.
