### ISSUE TITLE
dojo-lite call made to js.arcgis.com

### ISSUE THREAD

**Issue by sevenninety** [Esri/arcgis-webpack-plugin#55]
## Description
I think I'm right in saying that the JS API and Dojo are all included locally within an application created using the arcgis-webpack-plugin - rather than being referenced from the DEFAULT_WORKER_URL location.

When inspecting network calls made to the Demo webpack application, it appears that dojo-lite.js is still being called from js.arcgis.com.

## Expected Behavior
dojo-lite.js should be referenced from the /dojo folder of the generated application.

## Actual Behavior
dojo-lite.js is called from js.arcgis.com.

## Possible Fix
Adjusting the path of the DEFAULT_WORKER_URL to point to the deployed dojo-lite.js appears to mitigate the issue.

## Steps to Reproduce
1. Create a webpack application using the Demo application [https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo](https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo)
2. Run the application
3. Inspect network calls in the browser Developer Tools.

## Context
I'm trying to deploy an application to an environment with no Internet access.

## Your Environment
* Version used: 4.12.2
* Browser Name and version: Chrome 75.0.3770.142
* Operating System and version (desktop or mobile): Windows 10 1803
* Link to your project if available: N/A

**Comment by odoe** [comment]
The current behavior is correct. Currently, the workers are loaded via the CDN, and each worker loads it's own instance of the `dojo-lite.js`. The `dojo-lite.js` is only copied over as a fallback if the CDN load fails, but then it is not using web workers if that happens.

This will change in an upcoming release, but there is no ETA on that. Thanks!
