### ISSUE TITLE
Broken with pnpm

### ISSUE THREAD

**Issue by earksiinni** [Esri/arcgis-webpack-plugin#56]
## Description
(Somewhere between a bug report and a feature request.)

[pnpm is an alternative package manager](https://pnpm.js.org/) and drop-in replacement for npm that uses a non-flat structure for `node_modules` to prevent duplication of dependency package installations across multiple projects on a given machine. This structure also prevents package A from arbitrarily reading files from package B unless package B is a dependency of package A. After npm and yarn, it's generally considered to be the third-most popular package manager (albeit a distant third).

(A couple of articles on pnpm's benefits:

[Why should we use pnpm?](https://www.kochan.io/nodejs/why-should-we-use-pnpm.html)
[pnpm's strictness helps to avoid silly bugs](https://medium.com/pnpm/pnpms-strictness-helps-to-avoid-silly-bugs-9a15fb306308))

While the `node_modules` spec doesn't mandate a flat directory structure, many packages assume one, which can cause problems when using pnpm. For @arcgis/webpack-plugin, https://github.com/Esri/arcgis-webpack-plugin/blob/master/lib/requiredPlugins.js#L135 attempts to copy a bunch of files from subdirectories of `node_modules`. This behavior breaks under pnpm because those subdirectories don't exist under the project's `node_modules` since they aren't direct dependencies of the project, but rather of the plugin.

cc: @zkochan

## Expected Behavior
Running webpack after installing and configuring `@arcgis/webpack-plugin` should work while using pnpm.

## Actual Behavior
The plugin complains about not having access to certain files in the project's node_modules directory that are actually from dependencies of the plugin rather than dependencies of the project.

<img width="710" alt="Screen Shot 2019-08-06 at 7 35 42 AM" src="https://user-images.githubusercontent.com/5427394/62551518-03e0b380-b821-11e9-945c-af3d768a4dde.png">

## Possible Fix
First, for any packages from which this package copies files, list those packages as dependencies in package.json.

Second, in https://github.com/Esri/arcgis-webpack-plugin/blob/master/lib/requiredPlugins.js#L135, instead of using `node_modules` as the `context` for CopyWebpackPlugin, leverage node's module resolution to find the exact path. Example:

```
new CopyWebpackPlugin([
  {
    from: path.dirname(require.resolve("dojo/resources/blank.gif")),
    to: "dojo/resources"
  },
  ...
}   
```

Not 100% sure if this will work because I'm not totally sure whether it will attempt to start node's resolution algorithm relative to your project path (won't work) or the plugin package's installed path within pnpm's hierarchy (should work). (Thoughts, @zkochan?)

## Steps to Reproduce

1. Install pnpm
2. Set up project
3. Install `@arcgis/webpack-plugin` in the project using pnpm: `pnpm i @arcgis/webpack-plugin`
4. Configure project to use webpack and ArcGIS plugin
5. Run webpack

## Context

I'm unable to use this plugin with pnpm as intended. (Workaround: installing with pnpm's `--shamefully-flatten` option, which emulates npm's flat node_modules behavior.)

## Your Environment

* Version used: 4.12.2
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Debian 9

**Comment by zkochan** [comment]
Using Node's resolution algorithm + declaring the packages as dependencies should solve the issue.

(this will also make the project Yarn Plug'n'Play compatible, which like pnpm, does not allow accessing packages that are not declared as dependencies)
