### ISSUE TITLE
Errors when toggling vector tiles basemap

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-webpack-plugin#57]
## Description

When using the widget [basemapToogle](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-BasemapToggle.html) with a vector tile basemap, a whole bunch of errors is logged in the console when toogling basemap but the application seems to be working fine.
But, no error is logged with the same code using the CDN version of the JS API:
https://codepen.io/sasqwwqsasa/pen/WNejmBG
so I believe there is an issue with the webpack version.

## Expected Behavior

No error in the console

## Actual Behavior

A whole bunch of errors:
![error](https://user-images.githubusercontent.com/11556423/63846983-2a5fbd80-c98d-11e9-91c7-e1661c2c933b.PNG)

## Steps to Reproduce

1. Create a map having as basemap the following portal id [826498a48bd0424f9c9315214f2165d4](https://www.arcgis.com/home/item.html?id=826498a48bd0424f9c9315214f2165d4)
2. Add basemap toggle widget with for example "topo" webmap as nextBasemap
3. Run the application and toggle the basemap
4. Check the console

## Your Environment

* Version used: 4.12.1
* Browser Name and version: Chrome 76.0.3809.100
* Operating System and version (desktop or mobile): Windows
* Link to your project if available:

**Comment by Biboba** [comment]
I tested it on Chrome, Safari, Firefox, Edge, IE11 and it only occurs on Chrome and Safari

**Comment by Biboba** [comment]
An additionnal info, in webpack config, if I switch "esri-native-promise" to false no error is logged.
Also, I have a view toggle widget in my application a bit like this [example](https://developers.arcgis.com/javascript/latest/sample-code/views-switch-2d-3d/index.html) and when toggling the view to 3D, I have the same errors logged.
Any idea @odoe ?
Thanks !

**Comment by odoe** [comment]
Could be some underlying promise stuff we need to take care of. I'll do some further testing. I think errors could be safely ignored and there might be a flag to set in the webpack plugin build to suppress them. I'll investigate.

**Comment by Biboba** [comment]
Just an update that this issue still occurs using version 4.13.1
