### ISSUE TITLE
Duplicated packages in chunks?

### ISSUE THREAD

**Issue by roemhildtg** [Esri/arcgis-webpack-plugin#59]
This is more of a general question - I'm using the bundle analyzer to see what's causing large bundle sizes and I'm seeing lots of duplicated modules in chunks. Is this to be expected?

See how waterMaterialData appears at least 4-5 times in different chunks.

![image](https://user-images.githubusercontent.com/5471079/65463637-be526700-de1d-11e9-9902-a0c9a19df6e8.png)

**Comment by odoe** [comment]
This is currently how it works, I think because of the AMD dependencies. I thought webpack would handle it better, but so far it doesn't. We're working to improve this in a future release.
