### ISSUE TITLE
esri import is not working

### ISSUE THREAD

**Issue by sankargflexicious** [Esri/arcgis-webpack-plugin#61]
Issue: **Unable to import the Point, GraphicsLayer, webMercatorUtils from the esri.**

code snippet: 

import { Map } from "@esri/react-arcgis";
import { GraphicLayer } from '@esri/react-arcgis/layers/GraphicsLayer';
import {webMercatorUtils} from '@esri/react-arcgis/geometry/webMercatorUtils';
import {Point} from '@esri/react-arcgis/geometry/Point';

    mapMaker = () => {
      const { mapData} = this.props;

      if(mapData.length > 0 ){
          let map = new Map();
          map.removeAllLayers();
          let graphicsLayer = new GraphicLayer();
          map.addLayer(graphicsLayer);

          for(var index=0; index<mapData.length; index++){
            const data= mapData[index];

            if(data.latitude !== '0' && data.latitude !== null && data.latitude !== '' && !NaN(Number(data.latitude)) &&
            data.longitude !== '0' && data.longitude !== null && data.longitude !== '' && !NaN(Number(data.longitude))){
              this.createMarker(data);
            } 
          }
      }
    }

    createMarker = (data) => {
      const conversionToMap = webMercatorUtils.geographicToWebMercator(
        new Point(Number(data.longitude), Number(data.latitude))
      );

      const dataMap = new Point(conversionToMap.x, conversionToMap.y);
      return dataMap ;
    }

--> This is my snippet of code But not able to import the Point, GraphicsLayer, webMercatorUtils. How can I import it? 

getting error: 
**Module not found: Can't resolve '@esri/react-arcgis/geometry/Point'**

* Version used:
@esri/react-arcgis": "^4.0.0",
"react": "^16.7.0",
"react-dom": "^16.7.0",

Can anyone suggest me?

**Comment by odoe** [comment]
Sorry, it looks like you are trying to use the esri react project, not the webpack plugin this repo is for. You can make an issue here https://github.com/Esri/react-arcgis

**Comment by sankargflexicious** [comment]
Okay Sure. Thanks
