### ISSUE TITLE
Webpack build time error

### ISSUE THREAD

**Issue by xxxle0** [Esri/arcgis-webpack-plugin#62]
I have webpack build time error similar to https://community.esri.com/thread/217740-error-no-hook-for-resolver-normal-in-object-resolverfactory. 
## Description

When i integrate arcgis-webpack-plugin and run in my repo. I have this error. I think it come from compatible version dependencies in your plugin and webpack. My current version webpack 4.40.x 
and if i downgrade my webpack version to 4.8.0 -> it no crash in build time anymore but have another issue with dojo.js . See the image attach below. 

### **webpack version 4.40.x**
<img width="967" alt="Screen Shot 2019-10-24 at 11 41 54 PM" src="https://user-images.githubusercontent.com/18297839/67506813-ef8db380-f6b7-11e9-8252-79f15d9ad713.png">

### **webpack version 4.8.0**
<img width="964" alt="Screen Shot 2019-10-24 at 11 45 21 PM" src="https://user-images.githubusercontent.com/18297839/67507032-5b701c00-f6b8-11e9-9ab6-97c55e7ae62f.png">

## Expected Behavior
need support for new version webpack

**Comment by odoe** [comment]
Do you have a sample app that reproduces this issue?
I tested with [this demo app](https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo), which uses `4.41.*` and downgraded to `4.40.3` and no issues. It could be a config issue or maybe a conflict with another plugin.

Thanks!
