### ISSUE TITLE
Webpack build error 

### ISSUE THREAD

**Issue by tgeorges** [Esri/arcgis-webpack-plugin#63]
On Linux, when running webpack, i have this issue : 

This relative module was not found:

* ./BuildingFilterModeWireFrame in ./node_modules/arcgis-js-api/layers/support/BuildingFilterBlock.js

It breaks the build.

## Expected Behavior
build success
## Actual Behavior
build failures

## Possible Fix

The problem come from case in AMD require. A simple workaround is to modify API file import in arcgis-js-api/layers/support/BuildingFilterBlock.js, and replace BuildingFilterModeWireframe by BuildingFilterModeWireFrame

## Your Environment

* Version used:4.13
* Operating System and version (desktop or mobile): Linux Debian 10

**Comment by odoe** [comment]
Thanks! This should be fix in [`arcgis-js-api@4.13.2`](https://github.com/Esri/arcgis-js-api/releases/tag/4.13.2) which will propagate to the webpack plugin.
