### ISSUE TITLE
geometryJsonUtils not loaded

### ISSUE THREAD

**Issue by davidhanimann** [Esri/arcgis-webpack-plugin#64]
## Description
I'm using the webpack-plugin with Vue. Most arcgis modules work as expected by importing them like so: `import MapView from 'esri/views/MapView'`
Other modules simply don't work, e. g.
`import geometryJsonUtils from 'esri/geometry/support/jsonUtils'`

## Expected Behavior
All modules should be loaded and used through `import ` statements.

## Actual Behavior
Including `import geometryJsonUtils from 'esri/geometry/support/jsonUtils'` seems not to work, `geometryJsonUtils` is undefined at runtime. Building works however.

## Steps to Reproduce
1.
Download sample app: https://github.com/davidhanimann/arcgis-webpack-plugin-vue.git
2.
run `npm install` and `npm run serve`
3.
Build works, but see error in browser console

## Your Environment
* Browser Name and version: Chrome, Firefox
* Operating System: Windows 10
* Link to your project if available: https://github.com/davidhanimann/arcgis-webpack-plugin-vue

**Comment by Biboba** [comment]
Did you try 
```js
import * as geometryJsonUtils from 'esri/geometry/support/jsonUtils'
```

It is not a class but a module (low case)

**Comment by davidhanimann** [comment]
Looks like that was exactly the problem! Thank you @Biboa
