### ISSUE TITLE
IntegratedMeshLayer error

### ISSUE THREAD

**Issue by besLisbeth** [Esri/arcgis-webpack-plugin#65]
Hi, I've got an error after updating to 4.13 when adding IntegratedMeshLayer to the SceneView.

![image](https://user-images.githubusercontent.com/31760858/67752079-ffe8ba00-fa3a-11e9-8dc1-6e564a4014b8.png)
![image](https://user-images.githubusercontent.com/31760858/67752189-36bed000-fa3b-11e9-95c4-5d899e140b05.png)

### Possible fix
It looks to me like something transpiled wrong because when I'm downgrading the code, it works as it should (v. 4.11)

### Part of package.json
   ```
    "@arcgis/webpack-plugin": "4.13.0",
    "@babel/core": "^7.6.4",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-decorators": "^7.6.0",
    "@babel/plugin-proposal-export-default-from": "^7.5.2",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-modules-amd": "^7.5.0",
    "@babel/plugin-transform-runtime": "^7.6.2",
    "@babel/preset-env": "^7.6.3",
    "@babel/preset-react": "^7.6.3",
     ...
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.9",
    "webpack-dev-server": "^3.9.0"
```

* Version used:
4.13
* Browser Name and version:
Google Chrome version 78.0.3904.70 (Official Build) (64-bit)
* Operating System and version (desktop or mobile):
 Desktop, Windows 10

**Comment by odoe** [comment]
Do you have a sample project I can test with? I built a basic app using [this sample](https://developers.arcgis.com/javascript/latest/sample-code/layers-integratedmeshlayer/index.html) without issue, so it might be a config problem or similar. Thanks!

**Comment by Biboba** [comment]
Might not be the issue but I personally had a weird WebGL issue after upgrading to 4.13 and it was because I had forgotten to update the DEFAULT_WORKER_URL to 4.13 !
The rest of the application was working perfectly fine with JS API 4.13 and DEFAULT_WORKER_URL to 4.12

**Comment by besLisbeth** [comment]
@odoe, I'll try asap and write you the feedback.

But I also find another issue - is that OK, that in your folder `extras/dojo` you have dojo of version 4.12, and in [official site](https://js.arcgis.com/4.13/dojo/dojo-lite.js) the version is 4.13? I had an error with queryElevation in ElevationLayer, and I found out that if to replace code in the node_modules it starts working right (but not fixed IntegratedMesh, I'll explore it more).

**Comment by besLisbeth** [comment]
Fixed by adding next lines to the webpack.config.js:
```
resolve: {
            modules: [
                path.resolve(__dirname, '/src'),
                path.resolve(__dirname, 'node_modules/')
            ],
            extensions: ['.jsx', '.js', '.scss', '.css']
        },
```
