### ISSUE TITLE
TileLayer perfomance issue

### ISSUE THREAD

**Issue by besLisbeth** [Esri/arcgis-webpack-plugin#70]
Hi,
I found a strange performance issue - I added a TileLayer to the SceneView and started zooming in and out. In my Chrome's performance monitor DOM nodes began to increase, and the garbage collector not removing them - only a small part of them.

## Description
I used [jsapi-resources demo page](https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo), and  that's my code for adding a layer to the SceneView: 
```
import "./config";

import TileLayer from "esri/layers/TileLayer";
import ArcGISMap from "esri/Map";
import SceneView from "esri/views/SceneView";

const map = new ArcGISMap();

const view = new SceneView({
    map,
    container: "app",
    extent: {
        spatialReference: {
            wkid: 102100
        },
        xmax: -13581772,
        xmin: -13584170,
        ymax: 4436367,
        ymin: 4435053
    }
});

const tileLayer = new TileLayer({url: 'https://sampleserver6.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer'});

map.add(tileLayer);
```

## Expected Behavior
Garbage collector should remove the DOM nodes which are not using anymore.

## Actual Behavior
The amount of DOM nodes increases while using a map-based app for a long time. I added only a small part of the video - I zoomed in for a minute, or so, and the amount of DOM nodes increased from ~100 to 7,000. The garbage collector removed only a small part from this amount.

![arcgis_tilelayer](https://user-images.githubusercontent.com/31760858/68671198-6bf91100-0557-11ea-81da-e89d1c9799c7.gif)

## Steps to Reproduce
1. Create Map and SceneView
2. Add TileLayer to the Map
3. Start to zoom in and out
4. Open the performance monitor and watch the amount of DOM nodes and JS event listeners

## Context

We noticed a lack of performance when the users of our app using it for a long time.

## Your Environment
* Version used:
4.13
* Browser Name and version:
Google Chrome version 78.0.3904.70 (Official Build) (64-bit)
* Operating System and version (desktop or mobile):
Desktop, Windows 10

**Comment by RalucaNicola** [comment]
Thanks for the detailed bug report, we'll look into it. One question: 
> We noticed a lack of performance when the users of our app using it for a long time.

How much time does long time mean approximately?

**Comment by besLisbeth** [comment]
Thank you!
If to be more specific, it depends on the user's map interactions. For example, we noticed that the amount of DOM nodes can reach up to 20,000 nodes when the user moved the map and zoomed in and out constantly for about 15 minutes.
I also forget to mention, that if to use property 'basemap' the next way: 
```
  var myMap = new Map({
    basemap: 'streets'
  });
```
Then, the amount of DOM nodes stops above 1,000 (~600).

**Comment by RalucaNicola** [comment]
This will be fixed with 4.14. If you want to test it already, it will be in the next week's build on https://js.arcgis.com/next. If you're not familiar with next, you can read about it here: https://github.com/Esri/feedback-js-api-next/.

If it works then please close the ticket, otherwise let me know :)

**Comment by besLisbeth** [comment]
Thank you a lot, I'll test it as soon as it will be published at [the github page](https://github.com/Esri/feedback-js-api-next/)

**Comment by besLisbeth** [comment]
Thanks for your work, tiles working perfectly now!
