### ISSUE TITLE
TextSymbol text not rendering properly

### ISSUE THREAD

**Issue by sirishbyreddy** [Esri/arcgis-webpack-plugin#71]
## Description
TextSymbol characters not rendering properly

## Expected Behavior
It should display/render TextSymbol characters properly for different font types listed under the section
"Fonts for FeatureLayer, CSVLayer, and StreamLayer" in 
https://developers.arcgis.com/javascript/latest/guide/labeling/index.html

## Actual Behavior
Some text characters for different font types are not display/render properly

![TextSymbol_Error](https://user-images.githubusercontent.com/18139951/69132418-007ee880-0aef-11ea-8038-d71b43471f39.png)

## Steps to Reproduce
Its working without webpack: Refer to the below sample
https://codepen.io/sirishbyreddy/pen/NWWorRe

1. Create a Basemap using MapImageLayer
2. Create a graphic layer, add it to map
3. Create a Graphic with TextSymbol (with  Font.family, Font.style, and Font.weight properties) and add it to graphic layer

## Sample Code:
```
const textGraphic = new Graphic({
geometry: new Point({
  x: X_COORDINATE,
  y: y_COORDINATE,
  spatialReference: view.spatialReference
}),
symbol: new TextSymbol({
  color: "red",
  text: "abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  font: new Font({
	size: 12,
	family: "Arial",
	weight: "bold",
	style: "italic"
   })
 })
});
```

## Context
Unable to render Text properly

## Your Environment

Version used: 4.13.0
Browser Name and version: Chrome 78.0.3904.70 (Official Build) (64-bit)
Operating System and version (desktop or mobile):
Link to your project if available: Windows

**Comment by odoe** [comment]
Could you tell me what graphic card and drivers you are currently using?
Do you have a sample project this issue happens in?

So far, I'm unable to reproduce, but I'm wondering if it might be a hardware issue.

Thanks!
