### ISSUE TITLE
FeatureLayer delay - more than 1500 network requests by web workers

### ISSUE THREAD

**Issue by Dobkin** [Esri/arcgis-webpack-plugin#73]
## The Problem
Until recently we used esri-loader in our project, we decided to switch to the webpack-plugin mainly for better programming experience. Since we started using this plugin, we noticed major delay displaying a new feature layer on our map. This problem did not happen when we used esri-loader.

## More Details
We configured our web workers using the following:
```
import esriConfig from "esri/config";

const DEFAULT_WORKER_URL = "https://costum-server/esri/4.13/";
const DEFAULT_LOADER_URL = `${DEFAULT_WORKER_URL}dojo/dojo-lite.js`;

esriConfig.workers.loaderUrl = DEFAULT_LOADER_URL;
esriConfig.workers.loaderConfig = {
  baseUrl: `${DEFAULT_WORKER_URL}dojo`,
  packages: [
    { name: "arcgis-js-api", location: `${DEFAULT_WORKER_URL}esri` },
    { name: "dojo", location: `${DEFAULT_WORKER_URL}dojo` },
    { name: "dojox", location: `${DEFAULT_WORKER_URL}dojox` },
    { name: "dstore", location: `${DEFAULT_WORKER_URL}dstore` },
    { name: "moment", location: `${DEFAULT_WORKER_URL}moment` },
    { name: "@dojo", location: `${DEFAULT_WORKER_URL}@dojo` },
    {
      name: "cldrjs",
      location: `${DEFAULT_WORKER_URL}cldrjs`,
      main: "dist/cldr"
    },
    {
      name: "globalize",
      location: `${DEFAULT_WORKER_URL}globalize`,
      main: "dist/globalize"
    },
    {
      name: "maquette",
      location: `${DEFAULT_WORKER_URL}maquette`,
      main: "dist/maquette.umd"
    },
    {
      name: "maquette-css-transitions",
      location: `${DEFAULT_WORKER_URL}maquette-css-transitions`,
      main: "dist/maquette-css-transitions.umd"
    },
    {
      name: "maquette-jsx",
      location: `${DEFAULT_WORKER_URL}maquette-jsx`,
      main: "dist/maquette-jsx.umd"
    },
    { name: "tslib", location: `${DEFAULT_WORKER_URL}tslib`, main: "tslib" }
  ]
};
```
The app compiled successfully.
During runtime, when creating a new feature layer for the first time, there are more than 1500 network requests from web workers (while Chrome limits up to 6 parallel requests) -it which leads to major delay displaying the feature layer.
**1728 (!!!) requests** such as
```
https://custom-server/esri/4.13/views/2d/layers/features/Pipeline.js
https://custom-server/esri/4.13/core/tsSupport/declareExtendsHelper.js
```
Probably as a result of importing the FeatureLayer:
`import FeatureLayer from "arcgis-js-api/layers/FeatureLayer"`

What are we missing? Maybe should we build it somehow to reduce the amount of requests, or configure the API to do so?

We really really need your help, thanks in advance !

**Comment by odoe** [comment]
This is the first I've seen this. Can you please provide a sample project to reproduce. Thanks.

**Comment by ronavraham** [comment]
> This is the first I've seen this. Can you please provide a sample project to reproduce. Thanks.

Thank you @odoe for this fast reply.

We created this repo for you, demonstrating the issue, as you requested:
[https://github.com/ronavraham/esri-webpack](https://github.com/ronavraham/esri-webpack)

please look at the README to understand how to run this project.
It is a simple angular 8 application, which uses the webpack-plugin to create a map with a hybrid basemap and 1 feature layer, consumed for arcgis.com.
After compilation, go to your browser at http://localhost:4200/.

You would see it takes about **20 seconds** for the feature layer to get displayed, right after more than  **700 requests** being performed by the workers.
Just to mention, this issue doesn't happen when using esri-loader.
Thank you again for your help. 
Looking forward to your reply.

**Comment by ronavraham** [comment]
We managed to fix this issue by adding the following in our `tsconfig.json`:

`"esModuleInterop":true`

Don't know why, but its doing the job, now workers don't freak out. maybe @odeo can shed some light on this subject.

**Comment by odoe** [comment]
I think the interop gives the webpack build what it needs to work correctly. Not sure. I'll count it as a win. Thanks.
