### ISSUE TITLE
Wrong extras/dojo version. It is 4.12 version in npm!

### ISSUE THREAD

**Issue by stalniy** [Esri/arcgis-webpack-plugin#74]
## Description
Currently the version of extras/dojo.js is 4.12 for @arcgis/webpack-plugin 4.13! I see there was a commit a month ago which updates dojo.js to 4.13 version but it was not published! So, I can't use arcgis webpack plugin together with 4.13 version

## Expected Behavior
the version of extras/dojo.js needs to be 4.13 in npm

## Actual Behavior
the version of extras/dojo.js is 4.12 in npm

## Possible Fix
The version was updated but has not been released!

## Steps to Reproduce
1. `npm i @arcgis/webpack-plugin`
2. Check the comment at the beginning of `extras/dojo/dojo.js`  (`head -n 3 node_modules/@arcgis/webpack-plugin/extras/dojo/dojo.js`)

**Comment by odoe** [comment]
This should be published with `4.13.1`. Can't why remember why I didn't publish earlier.

**Comment by stalniy** [comment]
Cool! Thanks a lot for such a quick fix! 

And thanks for the awesome package!
