### ISSUE TITLE
Fail to import specific esri module

### ISSUE THREAD

**Issue by Dobkin** [Esri/arcgis-webpack-plugin#75]
When we use the following:
`import Converter from “esri/geometry/coordinateFormater”`

Converter is undefined on runtime.

Just to be clear, other imports of esri modules work properly.

What can cause this problem? 
Thanks in advance

**Comment by Biboba** [comment]
I believe it is the same issue as #64. 
import * as Converter from 'esri/geometry/coordinateFormater'

**Comment by Dobkin** [comment]
Yes, it works. Thank you!

**Comment by kirk-clawson** [comment]
I'd like to see esri address the inconsistencies here, since
`import geometryEngine from 'esri/geometry/geometryEngine';`
works just fine.
