### ISSUE TITLE
CoordinateConversion widget - global is not defined error

### ISSUE THREAD

**Issue by vaidotasp** [Esri/arcgis-webpack-plugin#80]
Using ArcGISPlugin and trying to utilize `CoordinateConversion` widget in our application fails due to error: `ReferenceError: global is not defined`.
Our webpack config has the required node settings:
```
node: {
  process:false,
  global: false,
  fs: 'empty'
}
```

### Environment
* Version used: esri.4.14/arcgis/webpack-plugin 4.14.0/typescript 3.7.4

Any ideas what would be potential fixes?

**Comment by dasa** [comment]
Try `node: false,` instead.

**Comment by vaidotasp** [comment]
Thank you @dasa , that seem to be solving some issues. Looks like widget is showing up okay, I am getting some warnings/errors during webpack compile step, not sure if those would introduce any unintended consequences:

```
WARNING in ./node_modules/arcgis-js-api/geometry/support/pe-wasm.js
Module not found: Error: Can't resolve 'crypto' in '/Users/vpiekus/code/gfw-mapbuilder/node_modules/arcgis-js-api/geometry/support'

ERROR in ./node_modules/arcgis-js-api/geometry/support/pe-wasm.js
Module not found: Error: Can't resolve 'fs' in '/Users/vpiekus/code/gfw-mapbuilder/node_modules/arcgis-js-api/geometry/support'

ERROR in ./node_modules/arcgis-js-api/libs/draco/draco_decoder.js
Module not found: Error: Can't resolve 'fs' in '/Users/vpiekus/code/gfw-mapbuilder/node_modules/arcgis-js-api/libs/draco'

ERROR in ./node_modules/arcgis-js-api/geometry/support/pe-wasm.js
Module not found: Error: Can't resolve 'path' in '/Users/vpiekus/code/gfw-mapbuilder/node_modules/arcgis-js-api/geometry/support'

ERROR in ./node_modules/arcgis-js-api/libs/draco/draco_decoder.js
Module not found: Error: Can't resolve 'path' in '/Users/vpiekus/code/gfw-mapbuilder/node_modules/arcgis-js-api/libs/draco'
ℹ ｢wdm｣: Failed to compile.
```

**Comment by dasa** [comment]
I think it's safe to ignore those. Those are the Node packages that aren't being polyfilled.

**Comment by vaidotasp** [comment]
Fair enough! Any way to tell webpack to ignore these in prod environments? Currently webpack builds in `dev` environment but fails on `prod`.

**Comment by odoe** [comment]
This worked in my local build for dev and prod without any compile warnings.

```
// webpack.config.js
    node: {
      process: false,
      global: false,
      Buffer: false, // add this line
      fs: 'empty',
    },
```

**Comment by vaidotasp** [comment]
Thank you all, @odoe , @dasa . This seems to solve my issue with building app and using ESRI's coordinate widget. 👍

**Comment by vaidotasp** [comment]
@odoe sorry to ping this issue again, but it seems like certain libraries (react-datepicker in particular) rely on `global` object and that breaks the app if I have the setup like below. Any insight into how can I hack around this limitation? ES Module transition will, I assume, solve all this but the date on that is unclear from what I gather. If you have any ideas, I'd appreciate it!
```
    node: {
      process: false,
      global: false,
      Buffer: false, // add this line
      fs: 'empty',
    },
```

**Comment by odoe** [comment]
Unfortunately no. I've run across some libraries where this is the case and for the moment, I don't have a workaround and this is a current limitation of the plugin.

**Comment by vaidotasp** [comment]
Understood, thanks for a quick reply!
