### ISSUE TITLE
ReferenceError: define is not defined

### ISSUE THREAD

**Issue by zhuminquan** [Esri/arcgis-webpack-plugin#82]
some functions does not work
## Description

Hi
When I upgrade to the latest version(4.15)，The following error occurred，I use the VUE+arcgis-webpack-plugin
app.js:7774 ReferenceError: define is not defined
    at Object../node_modules/arcgis-js-api/views/3d/camera/constraintUtils/tilt.js (app.js:2507)
    at A (app.js:1)
    at r (app.js:1)
    at Object../node_modules/arcgis-js-api/views/3d/camera/constraintUtils.js (app.js:2487)
    at A (app.js:1)
    at r (app.js:1)
    at Object../node_modules/arcgis-js-api/views/3d/state/controllers/global/ZoomStepController.js (app.js:3003)
    at A (app.js:1)
    at r (app.js:1)
    at Object../node_modules/arcgis-js-api/views/3d/input/handlers/DoubleClickZoom.j

## Steps to Reproduce

1.git clone my project
2.git uninstall @arcgis/webpack-plugin --save-dev //4.14.2
3.git install @arcgis/webpack-plugin --save-dev //4.15
4.npm run dev
6.open chrome browser and console

## Context

I try to update arcgis for js api  to latest version
## Your Environment

* Version used:
$ npm --version
6.13.4
$ node --version
v12.16.1
$ @vue/cli  --version
v4.2.3
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by zhuminquan** [comment]
I found this problem。
js file position：arcgis-js-api\views\3d\camera\constraintUtils.tilt.js
Interim solutions:
Replace arcgis-js-api(v4.14)'s  tilt.js  with arcgis-js-api(v4.15)'s  tilt.js
I wish the authorities can fix the bug as song as possible。
thanks

**Comment by odoe** [comment]
Do you have a sample repro project? I'm not currently able to repro with an existing application.
Thanks.
