### ISSUE TITLE
[esri.views.2d.layers.FeatureLayerView2D ]controller.setHighlight is not a function

### ISSUE THREAD

**Issue by devilsbibble** [Esri/arcgis-webpack-plugin#83]
## Description
FeatureLayer popupTemplate cant work correctly
## Expected Behavior
selected  feature highlight

## Actual Behavior
all features are highlighted
![20200422144344](https://user-images.githubusercontent.com/1435812/79949190-b936c280-84a7-11ea-8d6f-a365b81fb2b7.jpg)

## Possible Fix

I dont know

## Steps to Reproduce

```
this.map = new Map({
    basemap: "streets"
});

this.prospectLayer = new FeatureLayer({
    url: mapConfig.prospectFeature,
    definitionExpression: mapConfig.definitionExpression,
    popupTemplate:mapConfig.popupTemplate
});

this.map.add(this.prospectLayer);

let view = this.view =new MapView({
    container: this.mapRef.current,
    map: this.map,
    zoom: 4,
    center:[19.618944, 5.320372],
});
```
## Your Environment

* Version used:   "@arcgis/webpack-plugin": "~4.14.0"
* Browser Name and version: chrome 80
* Operating System and version (desktop or mobile): desktop
* Link to your project if available:

**Comment by odoe** [comment]
Do you have a sample application to repro this with? I can't reproduce this issue with FeatureLayer and Popups.

**Comment by devilsbibble** [comment]
Thank you for reply! @odoe 
I am  worried about package.json files was not installed correctly when` npm install` because of network speed and so on ,what is the js file that inclued the method controller.setHighlight located?  
How i make sure   package files was installed correctly?

**Comment by odoe** [comment]
If you really want to make sure you have correct packages, you can delete `node_modules` and `package-lock.json`, and run `npm install` again.

Thanks
