### ISSUE TITLE
Targeting ES6 In tsconfig.json

### ISSUE THREAD

**Issue by RyannGalea** [Esri/arcgis-webpack-plugin#87]
## Description
Not sure if this is the right repository for this or not, but I'm trying to get an idea on when we will be able to compile Arcgis using es6. 

## Context
I'm currently building an Angular Application and I am starting to have conflicts where it would be much better to set my compiler to es6 instead of es5. Currently, it won't compile properly with Arcgis using es6.

Any info appreciated.

**Comment by odoe** [comment]
You can target `es6`, maybe you mean `"module": "es6"`? That might be possible near the end of the year, still some other things that need to get done first. Thanks.
