### ISSUE TITLE
4.16 - ES6 imports not working with geometryEngine

### ISSUE THREAD

**Issue by roemhildtg** [Esri/arcgis-webpack-plugin#88]
## Description

I've been using the webpack plugin for past several releases now and the following has always worked: 

```javascript
import geometryEngine from 'esri/geometry/geometryEngine';

//...
geometryEngine.distance(...)
```

After running webpack, it looks like the output is like this: 
```
_geometryEngine.default.distance(event.mapPoint, geoms[index], 'feet');
```

In 4.16, this results in an error :

```
identifyTask.js?977b:314 Uncaught (in promise) TypeError: Cannot read property 'distance' of undefined
    at eval (identifyTask.js?977b:314)
    at Array.map (<anonymous>)
    at eval (identifyTask.js?977b:313)
    at Array.sort (<anonymous>)
    at eval (identifyTask.js?977b:309)
```

## Expected Behavior

I don't see any documentation in the release notes about changes to the Geometry engine - so I am wondering if this should continue working. We have dozens of modules that use this syntax in our applications that have stopped working correctly in this release and are looking for a recommended course of action. 

## Your Environment

* Version used: 4.16
* Browser Name and version: Chrome 83.0.4103.116
* Operating System and version (desktop or mobile): Windows 10

**Comment by dasa** [comment]
Can you try `import * as geometryEngine from 'esri/geometry/geometryEngine';`?

**Comment by roemhildtg** [comment]
I'll try that. Thanks @dasa!

**Comment by roemhildtg** [comment]
Yep - that did it. Thanks for the quick response!
