### ISSUE TITLE
making a CORS request to a localfile

### ISSUE THREAD

**Issue by jmanuelc87** [Esri/arcgis-webpack-plugin#9]
I have an error with the plugin.  It is trying to make a CORS request to a localfile.

`[esri.core.urlUtils] esri/config: esriConfig.request.proxyUrl is not set. If making a request to a CORS-enabled
 server, please push the domain into esriConfig.request.corsEnabledServers. Logger.js:25:1429`

`{
  "name": "urlutils:proxy-not-set",
  "message": "esri/config: esriConfig.request.proxyUrl is not set. If making a request to a CORS-enabled\n server, please push the domain into esriConfig.request.corsEnabledServers.",
  "details": {
    "url": "C:/Users/ssocial.dsg/Documents/mapas-dinamicos/node_modules/arcgis-js-api/core/workers/worker.js",
    "requestOptions": {
      "responseType": "text"
    },
    "ssl": false
  }
}`

`ERROR TypeError: t is null
Stack trace:
./node_modules/arcgis-js-api/views/2d/libs/gl-matrix/vec2.js/__WEBPACK_AMD_DEFINE_RESULT__</u.transformMat2d@http://localhost:4200/vendor.bundle.js:123725:2182
./node_modules/arcgis-js-api/views/2d/ViewState.js/__WEBPACK_AMD_DEFINE_RESULT__</__WEBPACK_AMD_DEFINE_RESULT__</t.prototype.toMap@http://localhost:4200/vendor.bundle.js:121361:4451
./node_modules/arcgis-js-api/views/2d/tiling/TileInfoView.js/__WEBPACK_AMD_DEFINE_RESULT__</__WEBPACK_AMD_DEFINE_RESULT__</o.prototype.getTileCoverage@http://localhost:4200/22.chunk.js:350:2076
./node_modules/arcgis-js-api/views/2d/tiling/TileStrategy.js/__WEBPACK_AMD_DEFINE_RESULT__</__WEBPACK_AMD_DEFINE_RESULT__</e.prototype.update@http://localhost:4200/22.chunk.js:446:772
./node_modules/arcgis-js-api/views/2d/layers/TiledLayerView2D.js/__WEBPACK_AMD_DEFINE_RESULT__</__WEBPACK_AMD_DEFINE_RESULT__</t.prototype.update@http://localhost:4200/22.chunk.js:254:2559
./node_modules/arcgis-js-api/views/2d/layers/LayerView2D.js/__WEBPACK_AMD_DEFINE_RESULT__</__WEBPACK_AMD_DEFINE_RESULT__</t.prototype.processUpdate@http://localhost:4200/common.chunk.js:8348:1862
e/this.update@http://localhost:4200/vendor.bundle.js:121265:1222
u@http://localhost:4200/vendor.bundle.js:110641:1103
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:6838:17
onInvokeTask@http://localhost:4200/vendor.bundle.js:57769:24
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:6837:17
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:4200/polyfills.bundle.js:6605:28
./node_modules/zone.js/dist/zone.js/</ZoneTask.invokeTask@http://localhost:4200/polyfills.bundle.js:6913:24
ZoneTask/this.invoke@http://localhost:4200/polyfills.bundle.js:6902:28
timer@http://localhost:4200/polyfills.bundle.js:8471:17
 core.js:1449`

**Comment by odoe** [comment]
Do you have a sample we can test with, I haven't seen that error before.

**Comment by jmanuelc87** [comment]
The branch md config contains the project that was configured with the ArcGISPlugin
[https://github.com/jmanuelc87/mapas-dinamicos/tree/md-config](url)

**Comment by odoe** [comment]
I got past the cors issue.

In `tsconfig.app.json` remove the `"module": "es2015"`, it's override the `"module": "amd"` in the main `tsconfig.json`.

_But_, Angular is using loader plugins to load modules like `app.component.html`, `app.component.ts`, and `app.module.ts`.

There is this bit in the doc related to this in the [CSS section](https://github.com/esri/arcgis-webpack-plugin#css).

```ts
import "css!./css/main.scss";
```

```js
// webpack.config.js
...
  plugins: [
    ...
    // For plugins registered after the ArcGISPlugin, data.request has been normalized and
    // resolved to an absMid and other mappings and aliases have been applied.
    // You will need to update the loader plugin appropriately.
    new webpack.NormalModuleReplacementPlugin(/^css!/, function(data) {
      data.request = data.request.replace(
        /^css!/,
        "!style-loader!css-loader!sass-loader?indentedSyntax=false"
      );
    })
...
```

You can refer to [this section](https://github.com/OpenNTF/dojo-webpack-plugin#order-of-plugin-registration) in the `dojo-webpack-plugin` doc about this.

I'm not exactly sure how to work around this, as it seems that the `@ngtools` loader is used extensively when modules are loaded via decorators.

**Comment by andygup** [comment]
I'm not sure if this is related, but try using a slightly different syntax in `main.ts` to import the esri config file:


```js

import './config';

```

Note that `config.ts` doesn't export anything since it's not a valid module, it's just a static file. It's possible angular is getting confused by looking for an actual module called `config`.

**Comment by odoe** [comment]
Closing this until angular-cli 6.1, we'll address it as a new issue.

**Comment by atdiff** [comment]
I'm encountering this error as well. For the time being, I've edited my local version of the workerFactory.js to use a path of "arcgis-js-api/core/workers/worker.js" instead of "./worker.js".  I believe it has to do with how webpack is trying to bundle the file.
So with that change, I've gotten past the error and not getting any errors in the console, but the map isn't displaying.
