### ISSUE TITLE
Issue with esri/smartMapping/statistics/heatmapStatistics with 4.16.2 version

### ISSUE THREAD

**Issue by Rishi1979** [Esri/arcgis-webpack-plugin#90]
## Description
When used import HeatmapStatistics=require('esri/smartMapping/statistics/heatmapStatistics') and tried to call HeatmapStatistics.then, encountered below errors (recorded in console)
![Error1](https://user-images.githubusercontent.com/68419807/87765661-a7687f80-c84a-11ea-86a7-d350976d3029.PNG)

## Expected Behavior
Import HeatmapStatistics=require('esri/smartMapping/statistics/heatmapStatistics') should work without any error and return the output when called HeatmapStatistics.then()

## Actual Behavior
It was working fine with 4.15

## Possible Fix
Don't know.

## Steps to Reproduce
 let featLayerHM = new FeatureLayer({
        url: "XXXXXX",
      })
      view.map.add(featLayerHM);
      let heatMapStats: HeatmapStatistics = HeatmapStatistics({
        layer:featLayerHM1,
        view: view,    
        radius: 10
      })
     heatMapStats.then((stats) => {
        const heatmapRenderer = new HeatMapRenderer({
          blurRadius: Number(radiusVal),
          colorStops: [
            { ratio: 0, color: [133, 193, 200, 0] },
            { ratio: .2, color: [100, 153, 200, 0]  },
            { ratio: .4, color: [55, 153, 100, 0] },
            { ratio: .65, color: [255, 153, 100, 0] },
            { ratio: .8, color: [155, 153, 100, 0]},
            { ratio: 1, color: [55, 100, 200, 0] }
          ],
          minPixelIntensity: stats.min,
          maxPixelIntensity: stats.max
        })
    });

## Context
Unable to generate Heatmap on client side.

## Your Environment
Version used: 4.16.2
Browser Name and version: Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)
Operating System and version (desktop or mobile): Microsoft Windows 10 Pro (Desktop)
Link to your project if available: N/A

**Comment by odoe** [comment]
Do you have a sample project to repro this with? I just tried with a sample app and it worked. If I can repro, I can look into the issue further, thanks.

**Comment by Rishi1979** [comment]
Please try with portal item id "6553466517dd4d5e8b0c518b8d6b64cb" for the basemap in your sample application. We observed that, the error is occurring where View.spatialReference is other than WGS84 or WebMercator. Is this a limitation or BUG?

**Comment by odoe** [comment]
Hi @Rishi1979,
This also happens with the CDN using 4.16, so not webpack specific. We'll be looking into it.

Thanks!

**Comment by Rishi1979** [comment]
@odoe noted. Please let me know once the issue is fixed. Thanks.

**Comment by Rishi1979** [comment]
Hi odoe,
Please let us know if there is any update on the reported issue.

**Comment by odoe** [comment]
Someone is working on this issue. When a fix is available, it will first be on our [`@next`](https://github.com/Esri/feedback-js-api-next) release, then 4.17 by end of year. I don't have a current timeline though.

**Comment by Rishi1979** [comment]
Hi Odoe,
Please let me know if there is any further update on the above issue.
Thanks

**Comment by odoe** [comment]
Could you try with the latest 4.17 release and let me know if this issue still occurs. I think it is fixed now.

**Comment by Rishi1979** [comment]
Hi Odoe,

We have tried and issue is still same. This issue is not fixed in 4.17 release.
