### ISSUE TITLE
bundles amount increased dramatically in 4.16.2

### ISSUE THREAD

**Issue by RonMatrix** [Esri/arcgis-webpack-plugin#92]
After upgrade to 4.16.2, the number of bundles generated increased to **212** (when using `3d: false`),
in comparison to 4.15 where the number of bundles with the same webpack configuration is only **169**.

What happened? can it be decreased again?
Thanks.

**Comment by odoe** [comment]
This is a byproduct of additional features in the API. There isn't really much we can do at the moment to reduce the number of files output, even if not including 3d features. Build tooling will be improving later this year or early next.
