### ISSUE TITLE
Wrong zoom in 4.16.2

### ISSUE THREAD

**Issue by besLisbeth** [Esri/arcgis-webpack-plugin#93]
## Description

I've got a dozen of TileLayers and WebTileLayers, which are located on our internal server in the secured network. The first layer in the array is TileLayer. Maybe, it has wrong settings, I'm not the cartography specialist, but, it breaks the zoom for all the layers, that I have added to the map.  Zoom widget shows 0, while layers are downloaded with the zoom of 5.
When I change the order, and this broken TileLayer goes second in the row, everything works as it should - the zoom is 0, and all the layers are loaded with the zoom 0.

It seems to me, that somewhere in the code the map loads settings for itself from the first layer, and it breaks the zoom for all other layers.

I do not have such an issue in 4.15.2.

## Expected Behavior
Wrong settings for the first layer, added to the map should not break the settings for all the other layers.

## Actual Behavior
I assume, that min zoom for my first layer is 5, so map disallows to load layers with the zoom smaller than 5, however, zoom widget shows 0.

## Possible Fix
I changed the layer's order, but it's not the best way to fix it.

## Steps to Reproduce
I've got this TileLayer without access to the internet, so I upload a couple of screens from the internal server
![image](https://user-images.githubusercontent.com/31760858/88667041-88d77380-d0e9-11ea-854a-3408581140d8.png)
![image](https://user-images.githubusercontent.com/31760858/88666423-b8d24700-d0e8-11ea-9b2e-cd4def1adc53.png)

## Your Environment
* Version used: 4.16.2
* Browser Name and version: Chrome Version 84.0.4147.89 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Win10 64-bit, desktop

**Comment by odoe** [comment]
Does the same layer and same code work using the CDN of the API? Can you repro in codepen or the samples sandbox? https://developers.arcgis.com/javascript/latest/sample-code/

Do all the layers share the same tiling scheme?
Are the LoDs the same for all layers?

It's difficult to repro without some sample layers to work with. Are there similar layers you can find in ArcGIS Online that cause the same behavior?

**Comment by besLisbeth** [comment]
> Does the same layer and same code work using the CDN of the API? Can you repro in codepen or the samples sandbox?

Yes, I tried it in your sandbox, it seems, that the problem is with Arcgis update itself

> Do all the layers share the same tiling scheme?

No

> Are the LoDs the same for all layers?

No

I tried the next code in local sandbox: 

```
import "./config";
import TileLayer from "esri/layers/TileLayer";
import WebTileLayer from "esri/layers/WebTileLayer";
import ArcGISMap from "esri/Map";
import MapView from "esri/views/MapView";
import LayerList from "esri/widgets/LayerList";

const map = new ArcGISMap();

const view = new MapView({
    map,
    container: "app",
    extent: {
        spatialReference: {
            wkid: 102100
        },
    },
    zoom: 5,
    center: [32.37700182573525, 51.571642079194056]
});

const tileLayer = new TileLayer({url: "http://PATH/Vector/MapServer", title: 'Broken layer'});
const webTileLayer = new WebTileLayer({urlTemplate: "http://PATH/OSM/{level}/{col}/{row}", title: 'Normal layer'});
map.add(tileLayer);
map.add(webTileLayer);

view.when( () =>  {
    const layerList = new LayerList({ view });
    view.ui.add(layerList, "top-right");
});
```
If I add the broken layer first, I've got the next situation: 
![image](https://user-images.githubusercontent.com/31760858/88707480-f64fc800-d11a-11ea-902b-a85f80490442.png)
I cannot move away from the fifth zoom, however, the map shows that the current zoom is 0.


If to change the order of adding layers to the map: 
```
map.add(webTileLayer);
map.add(tileLayer);
```
![image](https://user-images.githubusercontent.com/31760858/88707216-a07b2000-d11a-11ea-9d63-b72480ad4d8d.png)
It shows 404 for this specific tile, but at least, the map tries to download it.


As I told you - this broken layer has no access from the internet, but I'll try to find out if we could provide some repro with it.

**Comment by besLisbeth** [comment]
Also, json from the broken layer: 

```
{"currentVersion":10.61,"serviceDescription":"1:50000","mapName":"Ukraine","description":"","copyrightText":"","supportsDynamicLayers":true,"layers":[{"id":0,"name":"Новый составной слой","parentLayerId":-1,"defaultVisibility":true,"subLayerIds":[1,16,23,33,37],"minScale":1155581.108577,"maxScale":0},{"id":1,"name":"Point","parentLayerId":0,"defaultVisibility":true,"subLayerIds":[2,3,4,5,6,7,8,9,10,11,12,13,14,15],"minScale":72223.819286,"maxScale":0},{"id":16,"name":"LINE","parentLayerId":0,"defaultVisibility":true,"subLayerIds":[17,18,19,20,21,22],"minScale":0,"maxScale":0},{"id":23,"name":"LINE2","parentLayerId":0,"defaultVisibility":true,"subLayerIds":[24,25,26,27,28,29,30,31,32],"minScale":0,"maxScale":0},{"id":33,"name":"LINE3","parentLayerId":0,"defaultVisibility":true,"subLayerIds":[34,35,36],"minScale":0,"maxScale":0},{"id":37,"name":"REGION","parentLayerId":0,"defaultVisibility":true,"subLayerIds":[38,39,40,41,42,43,44,45,46,47,48,49,50],"minScale":0,"maxScale":0},{"id":51,"name":"z_5-10","parentLayerId":-1,"defaultVisibility":true,"subLayerIds":[52,53,55,56,57],"minScale":0,"maxScale":1155581.108577}],"tables":[],"spatialReference":{"wkid":102100,"latestWkid":3857},"singleFusedMapCache":true,"tileInfo":{"rows":256,"cols":256,"dpi":96,"format":"PNG","compressionQuality":0,"origin":{"x":-2.0037508342787E7,"y":2.0037508342787E7},"spatialReference":{"wkid":102100,"latestWkid":3857},"lods":[{"level":0,"resolution":156543.03392800014,"scale":5.91657527591555E8},{"level":1,"resolution":78271.51696399994,"scale":2.95828763795777E8},{"level":2,"resolution":39135.75848200009,"scale":1.47914381897889E8},{"level":3,"resolution":19567.87924099992,"scale":7.3957190948944E7},{"level":4,"resolution":9783.93962049996,"scale":3.6978595474472E7},{"level":5,"resolution":4891.96981024998,"scale":1.8489297737236E7},{"level":6,"resolution":2445.98490512499,"scale":9244648.868618},{"level":7,"resolution":1222.992452562495,"scale":4622324.434309},{"level":8,"resolution":611.4962262813797,"scale":2311162.217155},{"level":9,"resolution":305.74811314055756,"scale":1155581.108577},{"level":10,"resolution":152.87405657041106,"scale":577790.554289},{"level":11,"resolution":76.43702828507324,"scale":288895.277144},{"level":12,"resolution":38.21851414253662,"scale":144447.638572},{"level":13,"resolution":19.10925707126831,"scale":72223.819286},{"level":14,"resolution":9.554628535634155,"scale":36111.909643},{"level":15,"resolution":4.77731426794937,"scale":18055.954822},{"level":16,"resolution":2.388657133974685,"scale":9027.977411},{"level":17,"resolution":1.1943285668550503,"scale":4513.988705},{"level":18,"resolution":0.5971642835598172,"scale":2256.994353},{"level":19,"resolution":0.29858214164761665,"scale":1128.497176},{"level":20,"resolution":0.14929107082380833,"scale":564.248588},{"level":21,"resolution":0.07464553541190416,"scale":282.124294},{"level":22,"resolution":0.03732276770595208,"scale":141.062147},{"level":23,"resolution":0.01866138385297604,"scale":70.5310735}]},"initialExtent":{"xmin":2877579.085489989,"ymin":5958145.306722073,"xmax":4051768.9161986834,"ymax":6909132.92566909,"spatialReference":{"wkid":102100,"latestWkid":3857}},"fullExtent":{"xmin":2448963.779188349,"ymin":5525723.283593131,"xmax":4480384.222500323,"ymax":6890789.862685631,"spatialReference":{"wkid":102100,"latestWkid":3857}},"minScale":1.8489297737236E7,"maxScale":4513.988705,"units":"esriMeters","supportedImageFormatTypes":"PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP","documentInfo":{"Title":"","Author":"","Comments":"ATO","Subject":"ATO","Category":"","AntialiasingMode":"None","TextAntialiasingMode":"Force","Keywords":"vector"},"capabilities":"Map,Query,Data","supportedQueryFormats":"JSON, AMF, geoJSON","exportTilesAllowed":false,"supportsDatumTransformation":true,"maxRecordCount":1000,"maxImageHeight":4096,"maxImageWidth":4096,"supportedExtensions":""}
```
