### ISSUE TITLE
When using  a method of the geometryEngine, an 'undefined' error is triggered

### ISSUE THREAD

**Issue by mihaSoro** [Esri/arcgis-webpack-plugin#94]
With the latest webpack plugin (4.16.3) when I use a method from the geometryEngine, I get an error "Cannot read property ... of undefined". The problem seems to be that the initial code:
geometryEngine.buffer is compiled to geometryEngine_1.default.buffer .

## Steps to Reproduce
   const buf =geometryEngine.buffer(new Point({x:25.5,y:45.5, spatialReference:{wkid:4326}}), 100, "meters");
   console.log(buf);

**Comment by dasa** [comment]
Can you see if this is same as #88?

**Comment by mihaSoro** [comment]
Oh yes, the same fix as #88 worked here as well. Thank you very much!
