### ISSUE TITLE
project method of esri/geometry/projection is not working with production build

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-webpack-plugin#96]
**project** method of **esri/geometry/projection** is not working with production (npm run build) build.
However, it's working fine with development (npm start)

## Expected Behavior

**projection.project** should work fine same like the development build

## Actual Behavior

![projection_project_error](https://user-images.githubusercontent.com/17163418/90635356-ad8fb880-e25b-11ea-912c-57898d02fb25.png)

## Steps to Reproduce

1. import * as projection from 'esri/geometry/projection';
2. call **projection.load()** in **postInitialize**
3. projection.project(geometry, this.view.spatialReference)

## Your Environment

* Version used: 4.16.3
* Browser Name and version: Google Chrome - Version 84.0.4147.135 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Desktop - Microsoft Windows 10 Pro
* Link to your project if available:

**Comment by rangasatishkumar** [comment]
Instead of calling **projection.load()** in **postInitialize**, called it just before the **projection.project** (refer below code). Errors disappeared in the console for production build.

`    if (!projection.isLoaded()) {`
      `await projection.load();`
    `}`

**Comment by slutske22** [comment]
This helped me with a related problem.  I was trying to `import projection from 'esri/geometry/projection'`, I didn't know I needed to do it as a `* as projection`.  

How do we know which modules can be imported directly, and which ones need a `* as module` syntax?
