### ISSUE TITLE
Build works on localhost but fails in Azure DevOps with "Module not found: Error: Can't resolve 'css-loader'"

### ISSUE THREAD

**Issue by slead** [Esri/arcgis-webpack-plugin#99]
## Description
I'm building a boilerplate React app using this ArcGIS-webpack-plugin, combined with React (based on Rene's blog post at https://www.esri.com/arcgis-blog/products/js-api-arcgis/mapping/using-react-with-the-arcgis-api-for-javascript/) 

It builds correctly on my localhost and compiles into a working app in the /dist directory. But when I try to build this app using the Azure DevOps pipeline, it fails with the error `Module not found: Error: Can't resolve 'css-loader'`. I'm not an Azure DevOps expert so I'm not sure why there is a difference in behaviour between the environments.

![Screen Shot 2020-10-07 at 10 03 19 am](https://user-images.githubusercontent.com/133596/95269082-63eb4380-0884-11eb-9dc2-d14cb9962fb6.png)

## Expected Behavior
App should build into the /dist directory (or the equivalent on Azure DevOps).

## Actual Behavior
Running on the Azure DevOps pipeline I see this error:

```
ERROR in multi ./node_modules/@arcgis/webpack-plugin/loader/dojo.js ./src/css/main.scss ./src/index.js
Module not found: Error: Can't resolve 'css-loader' in 'D:\a\1\s'
 @ multi ./node_modules/@arcgis/webpack-plugin/loader/dojo.js ./src/css/main.scss ./src/index.js index[0]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html 587 bytes {0} [built]
        + 1 hidden module
```

## Steps to Reproduce
I've placed an identical copy of the app at https://github.com/slead/React-ArcGIS-boilerplate if you have a chance to examine if for any errors. The full DevOps error log is [here](https://www.dropbox.com/s/ehkp88qpscf3sjy/Azure%20DevOpes%20log.txt?dl=0).

Thanks

**Comment by odoe** [comment]
I'm not sure why it would fail in a cloud environment, but my best guess is that some dependencies need to updated. The `css-loader` dep isn't that far behind at 3.6.0 with latest at 4.3.0. A couple have `npm audit` issues which might also be an issue, but not `css-loader`. First I've heard of it, but you can try to update everything and test it out.

**Comment by slead** [comment]
@odoe thanks for the tips. I spent a while on this but wasn't able to get it to work on Azure, so I started again based on another working app. 

I don't know what the original problem was, but here is the relevant snippet of my package.json in case it helps anyone else in future:

```
"dependencies": {
    "@arcgis/webpack-plugin": "~4.14.0",
    "@babel/polyfill": "^7.7.0",
    "bootstrap": "^4.4.1",
    "handlebars": "^4.5.3",
    "node-sass": "^4.13.0",
    "react": "^16.8.2",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-dom": "^16.8.2",
    "styled-components": "^4.1.1",
    "toastr": "^2.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/preset-env": "^7.1.6",
    "@babel/preset-react": "^7.0.0",
    "@types/arcgis-js-api": "~4.14.0",
    "@types/react": "^16.8.2",
    "@types/react-dom": "^16.0.7",
    "@types/styled-components": "^4.1.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-styled-components": "^1.8.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.6.0",
    "core-js": "^3.6.5",
    "css-loader": "^0.28.11",
    "html-loader": "^0.5.5",
    "html-webpack-inline-source-plugin": "^0.0.10",
    "html-webpack-plugin": "^3.1.0",
    "mini-css-extract-plugin": "^0.4.0",
    "optimize-css-assets-webpack-plugin": "^4.0.1",
    "prettier": "^1.15.2",
    "resolve-url-loader": "^2.3.0",
    "sass-loader": "^6.0.7",
    "style-loader": "0.20.3",
    "ts-jest": "^23.10.4",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "webpack": "^4.25.1",
    "webpack-cli": "^3.1.1",
    "webpack-dev-server": "^3.1.10"
  }
```
